### ISSUE TITLE
QuerySelectField slow validation if query returns lots of rows

### ISSUE THREAD

**Issue by Frozenball** [wtforms/wtforms#103]
[QuerySelectField](https://github.com/wtforms/wtforms/blob/master/wtforms/ext/sqlalchemy/fields.py) (at least in wtforms.ext.sqlalchemy.fields) will fetch a full list of items when validating, resulting in a unnecessary slow validation. Full list of items should only be fetched when needed.

**Comment by crast** [comment]
Does not compute.

How do you validate something against the choices without the list? And I would say the time of validation is "when needed"

**Comment by Frozenball** [comment]
How about just querying the database if the pk exists? e.g.

````python
def pre_validate(self, form):
   if not query_factory.filter_by(id=self.data).count():
      raise ValidationError('Not a valid choice')
````

Fetching the full list of choices is only required for rendering.

**Comment by orarbel** [comment]
@Frozenball having the same issue, but I'm using `model_form`. Any idea how to solve this?

**Comment by Frozenball** [comment]
I don't remember how I solved it. You could look at the source code and
subclass it.
