### ISSUE TITLE
Change default value of a SelectField after form creation

### ISSUE THREAD

**Issue by Flyflo** [wtforms/wtforms#106]
I think this issue is related to #16 but I have a code example:
```python
from wtforms import Form, SelectField


class TestForm(Form):
    select = SelectField(choices=[(1, 'First'), (2, 'Second')])


myform = TestForm()
myform.select.default = 2

print(myform.select)
# Return:
# <select id="select" name="select"><option value="1">First</option><option value="2">Second</option></select>

```
As you can see, the second option isn't selected. I don't think it's the intended behavior.

I made some modifications to the SelectField class but it's only a quick workaround (especially in *process_data*):
```python
    def iter_choices(self):
        current_value = self.data if self.data is not None else self.coerce(self.default)
        for value, label in self.choices:
            yield (value, label, self.coerce(value) == current_value)

    def process_data(self, value):
        if value is None:
            self.data = None
            return

        try:
            self.data = self.coerce(value)
        except (ValueError, TypeError):
            self.data = None
```

**Comment by skrcrc** [comment]
myform = TestForm()
myform.select.default = 2
myform.process()     // <-- you missed this  :)

**Comment by alex1007** [comment]
process() causes the failure of validate_on_submit(). Some values are lost.

**Comment by crast** [comment]
`myform=TestForm(select=2)`

**Comment by jpmaligne** [comment]
You can do `myform.select.process_data(2)` to set a value after the initialization of the form. This will result in a "selected value=2" in the <option>.

Yet, I don't know how to remove this "selected value" when we select another option (without JS or processing the form again). Any Ideas ?

**Comment by siccovansas** [comment]
This seems to be still an issue.

I tried all of the proposed solutions, but they don't seem to work.

**Comment by WTRipper** [comment]
> 
> 
> process() causes the failure of validate_on_submit(). Some values are lost.

That's true. However you can read the values before you call process().
Something like this:

    class TestForm(Form):
        select = SelectField(choices=[(1, 'First'), (2, 'Second')])

    @main.route('/my_view', methods=["GET", "POST"])
    def my_view():
    myform = TestForm()

    if myform.validate_on_submit():
        print(myform.select.data)
        # do something with the data here   
  
    myform.select.default = 1
    myform.process()    # calling process() afterwards
    return("mytemplate.html, form=form)

___

> 
> 
> This seems to be still an issue.
> 
> I tried all of the proposed solutions, but they don't seem to work.

For me the proposed solutions of @skrcrc and @jpmaligne work. However keep in mind that indexing starts at 0. So the example of @Flyflo does not work 100% with those solutions. If you only have 2 choices set default to 0 to get the first choice or default=1 to get the second choice.

**Comment by BobDenny** [comment]
Yes all I wanted was for  the select to be set when initially rendering and returning the form. @skrcrc is right. That caused it to work. Thanks!!

**Comment by olliebreeden** [comment]
For me, just changing the data changed the selected value without processing and still allowed for form.validate_on_submit()

------------------------------------
form= MyForm()
form.select.data = 1

if form.validate_on_submit():
    # do something

return("mytemplate.html, form=form)

**Comment by shawndcorn** [comment]
@TBaguette  When I try and use the JS solution you present, it changes the default choice as expected.  But then if a user tries to change from that default, the change doesn't take affect when they submit the form.  Did you have to do something else for a change to work correctly?
