### ISSUE TITLE
populate_obj creates dirty objects in session

### ISSUE THREAD

**Issue by snc-tolksdorf** [wtforms/wtforms#109]
if I use

form.populate_obj(user)

and the user has "active = True" and the new value for active is True, the user object is marked as dirty in the session because of

/wtforms/fields/core.py :: Field

    def populate_obj(self, obj, name):
        """
        Populates `obj.<name>` with the field's data.

        :note: This is a destructive operation. If `obj.<name>` already exists,
               it will be overridden. Use with caution.
        """
        setattr(obj, name, self.data)

should it be like this?

    def populate_obj(self, obj, name):
        if hasattr(obj, name) and getattr(obj, name) != self.data:
            setattr(obj, name, self.data)

**Comment by longhotsummer** [comment]
WTForms relies on the model to check if values have changed. For instance, SQLAlchemy does this for its models. You can call `model.active = True` as much as you like but SQLAlchemy will only write that change if it is different to what is in the database.

I don't think it should be the responsibility of WTForms to decide if a value has changed or not, that should be up to the model.
