### ISSUE TITLE
How to disable id autogeneration to all fields?

### ISSUE THREAD

**Issue by gabrielpugliese-luizalabs** [wtforms/wtforms#110]
I've been looking a lot for an answer before asking here.
How to disable auto generated ids in rendered html tags? I just want to pass a class to a field and do not to override `__class__` methods of all fields I would use.

```
{{ form.card_expiration_month(class_="card-expiration-month") }}
```

Renders this:

``` html
<select class="card-expiration-month" id="card_expiration_month" name="card_expiration_month"></select>
```

And I don't want to.

**Comment by i-am-david-fernandez** [comment]
Hello.

Is this constraint still in place? It appears so looking at the source (`widgets/core.py::Input.__call__(...)`) where a default `id` attribute is specified. To make things even worse, it appears (`fields/core.py::Field.__init__(...)` line 107) that one cannot even specify an empty/`None` id at the point of field instantiation.

Any reason why this design choice was made? It essentially means one cannot use multiple forms on a single page (assuming the forms have at least a built-in CSRF hidden field and a submit button, which I expect would typically be the case) and have that page be valid/well-behaved (that is, one ends up with duplicated element ids (e.g., multiple `csrf_token` and `submit` ids).

While I appreciate that one can remove this constraint with custom widgets, that places a potentially considerable effort requirement on users (of this package).

**Comment by davidism** [comment]
When using multiple forms in a page, use the `prefix` arg to make the field names unique.
