### ISSUE TITLE
Set default for dynamic SelectMultipleField

### ISSUE THREAD

**Issue by ephexeve** [wtforms/wtforms#111]
I have a SelectMultilpleField where I set the choices dynamic (I query the database to get the new choices), since the user has his choices in the database too, I query his choices to set as default. I tried this

    form = PersonalForm(request.form, obj=user)
    form.courses.choices = [(c.title(), c.title()) for c in get_distinct_courses()]
    form.courses.default = [(i.title(), i.title()) for i in get_user_courses(userid)]

But it doesn't seem to work, it doesn't select the default. How can I fix this? Thanks!

**Comment by crast** [comment]
You can solve it by sending the value as a keyword arg to the constructor `PersonalForm(..., courses=[i.title() for i in get_user_courses(userid)])`

**Comment by Sebi2020** [comment]
That does not work, tested with wtforms 2.3.1
