### ISSUE TITLE
StringField ignores default values

### ISSUE THREAD

**Issue by Atilla** [wtforms/wtforms#116]
Simple enough, Optional() and default="something" on a string field do not mix. 

The code for StringField explicitly sets the value to u'' if the field isn't present.

**Comment by Kazanz** [comment]
This is really backwards.  Making the default function work one way with IntegerFields and another way with StringFields is bad.  Identical kwargs on a identical functions in subclasses should have identical functionality.

The least you could do is change the naming conventions.
