### ISSUE TITLE
Clean API consistent way form-level validation in WTForms

### ISSUE THREAD

**Issue by eneepo** [wtforms/wtforms#118]
First of all I want to appricaite all of the maintainers and contributors for such a useful package. It keeps a lot of pain away.

And now a little feature request :) I think there's a need for easy to use form-level validaton, or at least a clean way to send validation errors that are done in views. To work around this I use flash messages but there should be a better way to handle. So I think it would be a nice little feature.

**Comment by crast** [comment]
Duplicate of #55
