### ISSUE TITLE
Multiple forms, default values get lost

### ISSUE THREAD

**Issue by xtsimpouris** [wtforms/wtforms#119]
I am trying to implement two forms within the same view. and submitted data are processed in the same view. In each form there are some hidden input boxes (a form id, etc). These hidden values are populated with the default parameter and whenever I have POST data, I try to identify what happens form the hidden values. However, when I submit the first form, the default values for the second forms, are never set (they are just empty). The same happens when I submit the second form. So, when I submit the second form, after submitting the first one, all hidden values are corrupted.
The problem still exists even with using the prefix parameter in each form.

I can't figure out if I am not using the forms right, or it is at some point a bug.
An idea to avoid the problem was to use hardcoded 
```<input id="formLogin-idForm" name="formLogin-idForm" type="hidden" value="formLogin">```
 instead of just a
```{{ form_login.idForm }}``` which apparently is just a bad hack

Thank you very much for your support and time.

**Comment by DmonteiroD** [comment]
Any update about this? I am having exactly the same issue as you can see here. http://stackoverflow.com/questions/31242772/multiple-forms-in-the-same-page-keep-the-pre-populated-data-when-submitting
