### ISSUE TITLE
MultipleSelectField validation fails on valid data

### ISSUE THREAD

**Issue by bsherry** [wtforms/wtforms#122]
It may be that I'm misunderstanding how MultipleSelectField should be used, but I don't think MultipleSelectField is correctly validating data.  Take this script (main() added so it can be called within a flask app):
```
from flask.ext.wtf import Form, SelectMultipleField
from werkzeug.datastructures import MultiDict

class MyForm(Form):

    myField = SelectMultipleField('myField', choices=[('hello', 'hello'), ('world', 'world'), ('other', 'other')])

def main():
    data = MultiDict()
    data['myField'] = ['hello', 'world']

    f = MyForm(data)
    if f.validate():
        print "We have passed"
    else:
        print "We have failed"
```
This will fail.  The reason from digging around in the code is that in field.process there is:
```
self.raw_data = formdata.getlist(self.name)
```
Which makes our input [['hello', 'world']], and then in SelectMultipleField we in process_formdata:
```
self.data = list(self.coerce(x) for x in valuelist)
```
which will coerce our list into a string, and thus fail the validation.  I believe, much like in SelectField, we want to select out the first element of this list:
```
self.data = list(self.coerce(x) for x in valuelist[0])
```
When I made this change locally the validation passed correctly (although I'm unsure about wider ramifications).

**Comment by crast** [comment]
I don't believe you're using werkzeug's multidict properly.  I believe you need to assign the list of values using the [setlist](http://werkzeug.pocoo.org/docs/0.9/datastructures/#werkzeug.datastructures.MultiDict.setlist) method.
