### ISSUE TITLE
Use of (built-in) coerce as parameters

### ISSUE THREAD

**Issue by wenzul** [wtforms/wtforms#138]
I think it's not a good style to use _coerce_ as an (optional) parameter in methods.

Not least, as far as I can see, [documentation breaks because of that](http://wtforms.readthedocs.org/en/latest/fields.html?highlight=selectmultiple#wtforms.fields.SelectMultipleField) and github highlights it as a keyword as well.

**Comment by crast** [comment]
This is a good point, though changing this is a breaking change, so would need to go in WTForms 3.0.

Luckily,  WTForms 3.0 is actually not very far out at all, it's something I've been working on secretly, and a complete re-think of some core bits of WTForms.

**Comment by davidism** [comment]
`coerce` was removed in Python 3. I don't think we need to change this.
