### ISSUE TITLE
CSS class parameter for object initalization

### ISSUE THREAD

**Issue by digitalcraftsman** [wtforms/wtforms#139]
Would it be possible to implement a parameter for custom CSS classes to form objects while defining them inside a class? Something related is already possible if you code the the parts of the form yourself in the templates,  but in my usecase Flask-Bootstrap provides the `quick_form()` method for doing this automatically. So it's necessary to define the class parameter in the form class itself.

As small example:

```
class LoginForm(Form):
    username = StringField('Username:', validators=[Required()])
    password = PasswordField('Password', validators=[Required()])
    submit = SubmitField('Login',classes=['pull-right', 'btn-lg'])
```

**Comment by crast** [comment]
The feature won't look quite the same, but there will be some tools to help you do this in WTForms 3.0

**Comment by davidism** [comment]
This is implemented now with render_kw, a dict of attributes.
