### ISSUE TITLE
Unable to render a working BooleanField as a HiddenInput

### ISSUE THREAD

**Issue by kaiserfro** [wtforms/wtforms#140]
I have a situation where I'd like to render a BooleanField as a HiddenInput instead of a CheckboxInput.  It almost works, except for the initial rendering of the field.

My form definition has something like:
```
my_field = fields.BooleanField(widget=widgets.HiddenInput())
```
The form then manipulates the field using some javascript, then on submit, the value is properly coerced into the proper python type.  I can then use that value and save it into the database.

The only issue is when the field is rendered using:
```
form.my_field()
```
The value that the HiddenInput has in it is always 'y'.  I have to change the code to read as:
```
form.my_field(value=field.data)
```
Which seems too excessive.  The CheckboxInput widget uses field.data to determine the "checked" state of the checkbox, but HiddenInput uses _value() to determine the value.  For a BooleanField _value() depends on the data from the form, but in my case there is no data from the form yet.

It feels like the BooleanField's _value() method should be fixed somehow to make this feel less awkward.

**Comment by karland** [comment]
I am not sure, if this answer helps you. I have experimented with the `BooleanField` myself and initially came to the same conclusion. However, further experiments led me to the following situation. The `BooleanField` will be checked if you pass the `default` option with any value different from `None`. 

```
checkbox = BooleanField(default='checked')
```

This also populates the `checkbox.data` field with `True`. The documentation was not explicit on it, so I created this [PR #177](https://github.com/wtforms/wtforms/pull/177)

**Comment by crast** [comment]
This is actually a weird issue with how the HTML spec defines hidden fields... they can never be omitted and they apply to all forms on the page, regardless of whether they are actually lexically inside that `<form>` tag.

You can get around the blank value thing by using the `false_values` parameter to BooleanField and making sure that the default value is ignored
