### ISSUE TITLE
Generalized whitespace stripping for form fields

### ISSUE THREAD

**Issue by tom-dignan** [wtforms/wtforms#148]
I think it's an appropriate feature to add to WTForms. If you agree, where would the best place to add it be?

**Comment by crast** [comment]
You can do it in WTForms 2.x by using the [bind_field](http://wtforms.readthedocs.org/en/2.0.2/meta.html#wtforms.meta.DefaultMeta.bind_field) primitive on `class Meta`

Because class Meta can be inherited, you can actually then set up your own new base form primitives:

```python
class MyBaseForm(Form):
    class Meta:
        def bind_field(self, form, unbound_field, options):
            filters = unbound_field.kwargs.pop('filters', None) or []
            filters.append(my_strip_filter)
            return unbound_field.bind(form=form, filters=filters, **options)
```

Now, just inherit MyBaseForm for all your forms and you're good to go.

**Comment by ThiefMaster** [comment]
Does adding default filters somehow modify the process of unbound fields being bound to a form instance? I'm using a `QuerySelectMultipleField` where I'm assigning the `query` property after creating an instance of the form and as soon as there's a filter set - even if it's just `lambda x: x` - processing my form fails because `query` is None.

**Comment by ThiefMaster** [comment]
Found another bug: popping the `filters` kwarg will break all but the first instance of the form if there were additional filters. Using `get` instead of `pop` fixes this.

**Comment by pcraig3** [comment]
I've just been trying to implement this, but unfortunately, it doesn't seem to be working for `FieldList`s.  Binding filters is working quite nicely for regular fields, but trying to add them onto a `FieldList` throws the following error:
```
TypeError: FieldList does not accept any filters. Instead, define them on the enclosed field.
```

At the moment, the `bind_field` method of my subclassed `Form` looks like this:
```python
def bind_field(self, form, unbound_field, options):
            filters = unbound_field.kwargs.get('filters', [])
            if unbound_field.field_class is not FieldList:
                filters.append(strip_input)
            return unbound_field.bind(form=form, filters=filters, **options)
```

I know I could add the filter to the Field I'm passing into the FieldList (`FieldList(StringField('Name', filters=[some_filter]))`), but it seems to me that that somewhat defeats the purpose of subclassing the form to begin with.

What would be the problem with allowing filters passed in to a `FieldList` to be passed on to enclosed fields?  I'm thinking about changing [this line here](https://github.com/Khan/wtforms/blob/master/wtforms/fields/core.py#L834) to something like:
```python
field = self.unbound_field.bind(form=None, name=name, prefix=self._prefix, id=id)
``` 

I could open a pull request unless there are objections?

**Comment by ThiefMaster** [comment]
I have this in my base Form class
```
    class Meta:
        def bind_field(self, form, unbound_field, options):
            # We don't set default filters for query-based fields as it breaks them if no query_factory is set
            # while the Form is instantiated. Also, it's quite pointless for those fields...
            # FieldList simply doesn't support filters.
            no_filter_fields = (QuerySelectField, FieldList)
            filters = [strip_whitespace] if not issubclass(unbound_field.field_class, no_filter_fields) else []
            filters += unbound_field.kwargs.get('filters', [])
            bound = unbound_field.bind(form=form, filters=filters, **options)
            bound.get_form = weakref.ref(form)  # GC won't collect the form if we don't use a weakref
            return bound
```

**Comment by pcraig3** [comment]
Right, so you've just evaded it as well.
What's your opinion of being able to pass filters to FieldList which would then be bound to its enclosed fields?  Would that make sense, or am I not thinking generally enough?

**Comment by crast** [comment]
@pcraig3 `bind_field` is called for the field inside the FieldList so it will get handled anyway
