### ISSUE TITLE
Pass a list of fieldnames to populate_obj

### ISSUE THREAD

**Issue by typology** [wtforms/wtforms#162]
Hi,
I think it would be useful to be able to pass a list of field names to include in populate_obj
and also if most of the fields will be copied, a parameter of fields to exclude

for example:

form.populate_obj(user, include=['name', 'phone', 'email'])
form.populate_obj(user, exclude=['special_field'])

**Comment by bngsudheer** [comment]
Makes sense. I can write the code if it is likely to be accepted.

**Comment by aphillipo** [comment]
Yes - I really like this idea too - populate_obj is currently useless on more complex models as you can't set values for things that don't exist (at least in Flask-SQLAlchemy).

**Comment by bngsudheer** [comment]
There is already a pull request for this - https://github.com/wtforms/wtforms/pull/159

**Comment by crast** [comment]
Superceded by both #159 and #147
