### ISSUE TITLE
Could not find field converter for postgresql.CIDR

### ISSUE THREAD

**Issue by kalombos** [wtforms/wtforms#163]
Hello, i used  WTForms 1.0.3 and it worked fine. I tried to upgrade it to 1.0.5 (or 2.0.2) and i got an exception in model_form function: wtforms.ext.sqlalchemy.orm.ModelConversionError: Could not find field converter for net (<class 'tools.database.models.Cidr'>). Cidr is my class that extend default postgresql.CIDR class.
Could you explain me how to use extra_converters option, because i didnt find any example of it? TextAreaField without validators would be enough for me.

**Comment by crast** [comment]
This is a bug reporting process, not a support forum.

These kind of questions are better posted on http://stackoverflow.com
