### ISSUE TITLE
Add an id prefix

### ISSUE THREAD

**Issue by ThiefMaster** [wtforms/wtforms#167]
Especially for forms using GET, having a prefix on the field names is rather ugly, but having a prefix on the field IDs almost always makes sense to avoid potential clashes with other items. It would be nice if there was a separate attribute for that.

**Comment by aphillipo** [comment]
You could just do this in your rendering field macros/templates?

<label for="{{ 'prefix-'+f.id }}">{{ f.label.text }}</label>
{{ f(id='prefix-'+f.id) }}

And then not prefix the form?  I looked at the source to check some things but I haven't tested it.

**Comment by openbrian** [comment]
This is exactly the feature I need.
