### ISSUE TITLE
If the `obj` contain the matching keyword argument on creation, I would expect it to be overridden instead of being ignored.

### ISSUE THREAD

**Issue by lipis** [wtforms/wtforms#168]
https://github.com/wtforms/wtforms/blob/master/wtforms/form.py#L264-L267

It is more natural to think that if provided with the same argument that the object already has the value to be overridden, otherwise why the user should even put there.

Here is an example: very often some objects contain keys and their text representation is a bit different from the actual value. So when generating the choices I'm using their `urlsafe` version

```python
user = {
  name: 'Jon',
  color_key: Key(....),
}
form = UserForm(obj=user, color_key=user.color_key.urlsafe())
form.color_key.choices = [(color.urlsafe(), color.hex) for c in colors]
```

Of course later in the `validate_on_submit` we'll have to do something about, but that's another story which should happen anyway. Overriding by default makes sense since this will happen by the user it's kind of more expected behaviour.

**Comment by crast** [comment]
I'm not sure what you're asking here.

In either case, the whole input flow is completely rewritten in WTForms3
