### ISSUE TITLE
Input class not generating XHTML-compliant element

### ISSUE THREAD

**Issue by nvitucci** [wtforms/wtforms#180]
I believe the Input class does not generate an XHTML-compliant 'input' element. Using form.hidden_tag() (from Flask) results in an element like the following:

```html
<div style="display:none;"><input id="csrf_token" name="csrf_token" type="hidden" value="..."></div>
```

which is not compliant with the XHTML 1.1 standard as the "input" element is not closed at the end.

**Comment by yggi49** [comment]
Have a look at #173 and #174; this is by design.

**Comment by nvitucci** [comment]
So should I wait for a PolyglotForm to be added? Or what else do you recommend?

**Comment by yggi49** [comment]
A solution to your problem *might* be added in WTForm’s next major release, if at all.

**Comment by crast** [comment]
Right now, in wtforms 2.x, we output HTML which happens to be in the HTML-compact syntax, which is not XHTML-compatible like polyglot.

We're working on support for multiple rendering outputs without a ton of rewriting of widgets, it's going to be  a major feature of [WTForms 3.0](https://github.com/wtforms/wtforms/issues/154)

**Comment by yggi49** [comment]
For the time being, [`WTForms-Polyglot`][1] is now available on PyPI, providing `PolyglotForm`.  A companion package for Flask (Flask-WTF-Polyglot) will follow.

[1]: https://pypi.python.org/pypi/WTForms-Polyglot

**Comment by yggi49** [comment]
[`Flask-WTF-Polyglot`][1] is now also on PyPI.

[1]: https://pypi.python.org/pypi/Flask-WTF-Polyglot/

**Comment by nvitucci** [comment]
Great news! Thanks, I'll give it a try.

**Comment by yggi49** [comment]
[`WTForms-Polyglot`][1] now also includes a custom `SubmitField` implementation that uses `<button>` instead of `<input>` for rendering.

[1]: https://pypi.python.org/pypi/WTForms-Polyglot
