### ISSUE TITLE
Dynamically added fields to a form don't bind upon subclass instance

### ISSUE THREAD

**Issue by petehuang** [wtforms/wtforms#189]
relevant code here: https://gist.github.com/petehuang/cf3c947aeeba103b5b06

I'm subclassing the form and setting attributes within the view. However, when I instantiate the subclass, it's not binding the fields that I had dynamically set, only the ones you set as static attributes.

Any advice?

**Comment by crast** [comment]
is that class actually inside the view?

http://wtforms.readthedocs.org/en/latest/specific_problems.html#dynamic-form-composition
