### ISSUE TITLE
Can't set "selected" option in QuerySelectField

### ISSUE THREAD

**Issue by d2f** [wtforms/wtforms#194]
method: QuerySelectField.iter_choices()
  line: yield (pk, self.get_label(obj), obj == self.data)
  obj == self.data  (True or False to set selected option)
It seems that obj and self.data are not of the same type and test is always False.

method: QuerySelectMultipleField.iter_choices()
  line: yield (pk, self.get_label(obj), obj in self.data)
  same remark as  QuerySelectField

Is it for this reason i can't set "selected" option?

In my case if  "id" is my primary key:
  obj.id == self.data test performs.

**Comment by crast** [comment]
all `wtforms.ext` packages are deprecated in WTForms core, and will be removed in WTForms 3.x, At this point they are no longer receiving new feature updates. Submit your PR to https://github.com/wtforms/wtforms-sqlalchemy instead
