### ISSUE TITLE
Min/max values IntegerRangeField

### ISSUE THREAD

**Issue by Garito** [wtforms/wtforms#195]
Hi!
I would like to use min & max values for a range field but I can't find the correct way

Could you point me how to do so?

THanks!

**Comment by Garito** [comment]
Hello?

**Comment by ChaoticMind** [comment]
https://wtforms.readthedocs.org/en/latest/validators.html#wtforms.validators.NumberRange

**Comment by Garito** [comment]
Yeah, I'm using it. Sorry I was meaning to add them to the widget like:
<input type="range" min="1" max="10" step="1">

**Comment by ChaoticMind** [comment]
I'm not on a dev machine to try it atm, but you could try passing min/max to the constructor when initializing the form (i.e. as **kwargs params). 

However, wtforms encourages you to do it in the template instead, because this deals with the frontend, See #130 and possibly #9 .

**Comment by Garito** [comment]
If I add min and max to kwargs the constructor raises an unknown attribute error

I've read them but giving the fact that I generate the form with a classical model_form pattern (https://github.com/MongoEngine/flask-mongoengine/blob/master/flask_mongoengine/wtf/orm.py) I can't figure out how to know if the field has min and max

An idea will be to check the validators searching for NumberRange and get its min max but how can I know this? This will be used in a jinja2 template so will be a pain in the ass to check for this

What do you suggest?

**Comment by crast** [comment]
Check changes from wtforms 2.1

**Comment by AugustAl** [comment]
> Hi!
> I would like to use min & max values for a range field but I can't find the correct way
> 
> Could you point me how to do so?
> 
> THanks!

I did it in template , as shown below:
```
{{ form.num_range_select.label }} {{ form.num_range_select(min='10', max='50') }}
```
