### ISSUE TITLE
Values present in obj not used when formdata does not contain key

### ISSUE THREAD

**Issue by Trii** [wtforms/wtforms#197]
I have a form that I am passing a POST object to as well as an entity to `obj=` in order to populate fields on an update that should not be edited by the user. In this case, event_template contains a field named `template_name` that is read only after the item is created. 

This is how I populate the form object on POST
```python
@webapp2.cached_property
def form(self):
    form = forms.EventTemplateForm()
    form.process(self.request.POST, obj=self.event_template)
    return form
```
This is the data I am verifying in the debugger
```python
(
    'template_name' in self.request.POST,
    self.event_template.template_name,
    form.template_name.data,
)
```
Here are the values. You can see that `form.template_name.data` is empty. I expect it to have a value since it exists in `self.event_template` which was passed as `obj=`
```
0 = {bool} False
1 = {str} 'trying again'
2 = {unicode} u''
```

**Comment by Trii** [comment]
Here is the culprit https://github.com/wtforms/wtforms/blob/master/wtforms/fields/core.py#L282

`self.process_formdata()` is passed an empty list when the name exists in `obj` but not in `formdata` which then overwrites `field.data` while preserving `field.object_data`. Is this intentional?

**Comment by prencher** [comment]
Yes, it's intentional. Please review the documentation: http://wtforms.readthedocs.org/en/latest/faq.html#why-does-blank-input-not-go-back-to-the-default-value

**Comment by Trii** [comment]
I see. I was looking in the docs for fields and forms, not the FAQ. Thanks!
