### ISSUE TITLE
form.validate() is always false when using the DELETE http method

### ISSUE THREAD

**Issue by nickjj** [wtforms/wtforms#199]
I'm using it with `Flask==0.10.1` and `WTForms==2.0.2`.
### Fail case

It always returns false on `form.validate()` but `form.errors` contains an empty list.

``` python
@admin.route('/foo', methods=['DELETE'])
def foo():
    form = Foo(request.form)
    if request.method == 'DELETE' and form.validate():
        return 'yep'
    else:
        return 'nope'
```

---
### Success case

Everything works as intended, notice that only the method changed. The form is identical.

``` python
@admin.route('/foo', methods=['POST'])
def foo():
    form = Foo(request.form)
    if request.method == 'POST' and form.validate():
        return 'yep'
    else:
        return 'nope'
```

---
#### Things to note
- The contents of the form doesn't seem to matter.
- I'm using middleware to transform a POST into DELETE, but by the time the route is processed, it's a legit DELETE.

**Comment by crast** [comment]
I suspect werkzeug is doing something funny when you transform the method, like maybe not parsing form data

**Comment by PlasmaSheep** [comment]
Could it be a CSRF error? IIRC, CSRF is not turned on by default on DELETE methods. What is the error given from the form?

**Comment by davidism** [comment]
Can't reproduce this. If it's still an issue, please include a minimal reproducible example.

```python
from flask import Flask, request
from wtforms import Form
from wtforms.fields import StringField
from wtforms.validators import DataRequired

class NameForm(Form):
    name = StringField(validators=[DataRequired()])

app = Flask(__name__)

@app.route('/', methods=['DELETE'])
def index():
    form = NameForm(request.form)
    return str(form.validate())

client = app.test_client()
r = client.delete('/', data={'name': 'wtforms'})
print(r.get_data(as_text=True))
# True
```
