### ISSUE TITLE
Feature: Allow FileField to take keyword argument 'accept'

### ISSUE THREAD

**Issue by tanj** [wtforms/wtforms#201]
Currently we can do
```python
>>>upload = FileField()
>>>upload()
u'<input id="upload" name="upload" type="file">'
>>>
```
The accept keyword argument is not allowed.

I'd like to be able to do

```python
>>>upload = FileField(accept='image/*')
>>>upload()
u'<input accept="image/*" id="upload" name="upload" type="file">'
>>>
```

**Comment by aphillipo** [comment]
When you display a field in your template you can pass kwargs:

    class MyForm(Form):
        upload = FileField('Upload:')

    form = MyForm()
    form.upload(accept='image/*')  # render this in your template...
    
The output from the form line above would be:

    u'<input accept="image/*" id="upload" name="upload" type="file">'

Does this help?

**Comment by tanj** [comment]
That is helpful, but it would be nice to be able to have that logic kept with the Form class. That way your client side filter and server side validation can be seen in the same place.

```python
class MyForm(Form):
    upload = FileField('Upload:',
                       [Regexp(u'^.*\.jpg$'), Optional()],
                       accept=u'image/jpg')
```

**Comment by aphillipo** [comment]
Actually looking at the code this should work:

from wtforms import widgets
from wtforms import StringField

class MyFileField(StringField):
    widget = widgets.FileInput(accept='image/*')

Simpler than I thought...
