### ISSUE TITLE
Override field's name attribute?

### ISSUE THREAD

**Issue by jmagnusson** [wtforms/wtforms#205]
I need compatibility with some existing HTML that uses dashes in the `name` attribute, but I have yet to find a way to override it with wtforms. [The documentation for `wtforms.fields.core.Field`](https://wtforms.readthedocs.org/en/latest/fields.html?highlight=selectmultiplefield#wtforms.fields.Field) mentions the following about `_name`:

> The name of this field, passed by the enclosing form during its construction. You should never pass this value yourself.

This makes me think that I should be able to override the name in the enclosing form. But in that case - where? Here's a failing test that shows what I'm expecting to be able to do:

``` python
import wtforms
from werkzeug.datastructures import ImmutableMultiDict


class MyForm(wtforms.Form):
    my_field_id = wtforms.IntegerField('My field', id='my-field',
                                       _name='my-field')


my_data = ImmutableMultiDict([('my-field', '2')])
my_form = MyForm(my_data)
assert my_form.my_field_id.name == 'my-field'  # Instead `my_field_id`
assert my_form.my_field_id.data == 2  # Instead `None`
```

Instead I have to use this custom field to get what I'm looking for:

``` python
import wtforms
class MyCustomIntegerField(wtforms.IntegerField):

    def __init__(self, *args, **kwargs):
        name = kwargs.pop('name', None)
        super().__init__(*args, **kwargs)
        if name:
            self.name = name
```

Am I missing something here?

**Comment by jmagnusson** [comment]
I noticed this is mentioned in #154:

>De-couple attribute names from field names
>Allow users to have fields with names containing "special" characters while still allowing the field to >function, just like SQLAlchemy with attribute vs column names.
>Default case (when attribute name unspecified) is still using attribute name munging for maximum >compatibility

Hopefully we can get it earlier though :wink:

**Comment by xealot** [comment]
Just ran across this today when integrating with a third-party that requires special characters in the form submission. Primarily `[` and `]`.

**Comment by crast** [comment]
Will be supported in 3.0 as you mentioned
https://github.com/wtforms/wtforms/issues/154

**Comment by bmwant** [comment]
@jmagnusson a workaround is to override form meta when binding a field.

```
from wtforms.meta import DefaultMeta

class BindNameMeta(DefaultMeta):
    def bind_field(self, form, unbound_field, options):
        if 'custom_name' in unbound_field.kwargs:
            options['name'] = unbound_field.kwargs.pop('custom_name')
        return unbound_field.bind(form=form, **options)
```
This allows you to provide a parameter `custom_name` to any field you want to override a name for.

```
class PostForm(Form):
    my_title = StringField(custom_name='my-title')
```
Just keep in mind that you have to subclass from your own `Form` that uses new meta:
```
import wtforms

class Form(wtforms.Form):
    meta = BindNameMeta
```

**Comment by pfubar** [comment]
thanks bmwant, i just needed to change meta to Meta.
```python
import wtforms

class Form(wtforms.Form):
    Meta = BindNameMeta
```

**Comment by qiangzhichen** [comment]
I Wonder how dose it work in 

> FormFiled
