### ISSUE TITLE
HTML5 number input attributes seem split across multiple interfaces

### ISSUE THREAD

**Issue by detly** [wtforms/wtforms#207]
Let's say I want a number input like this:

    <input
        id="size"
        name="size"
        type="number"
        min="10" step="10" value="100"
        required="true">

It seems that the only way to do this (Python 3, WTForms 2.0.2) is like so:

    #!/usr/bin/env python
    from wtforms import Form
    from wtforms.fields.html5 import IntegerField
    from wtforms.widgets.html5 import NumberInput

    class TestForm(Form):
        size = IntegerField(default=100, widget=NumberInput(step=10))

    print(TestForm().size(min=10, required=True))

This seems very strange to me — one attribute (`default`) is right there in the field. Another one (`step`) must be given as an argument to an argument of the field, overriding the default widget. Another two can only be given when the widget is rendered.

None of these attributes seem to be any more fundamental or UI specific than any others. They are all simply UX enhancements implemented by browsers. It took a fair few hours of searching through the documentation just to figure out how to do this.

Am I doing this wrong? If not, is there some overarching logic to this that would help guide me when trying to construct such forms?

**Comment by detly** [comment]
Looking at [`widgets.html5.py:84`](https://github.com/wtforms/wtforms/blob/master/wtforms/widgets/html5.py#L84), it might be sensible just to add the allowed HTML5 attributes (`min`, `max`) there alongside `step`, and maybe `required` should go in a common HTML5 input widget base... would such a change be useful?

**Comment by crast** [comment]
This should be resolved now in #233
