### ISSUE TITLE
FileField with validators.DataRequired() is not works.

### ISSUE THREAD

**Issue by ChameleonRed** [wtforms/wtforms#211]
`entityForm.validate() == False` when file is uploaded.

```
class AddFileForm(form.Form):
  seoProject = simple.HiddenField(validators=[validators.DataRequired()])
  name = core.StringField(validators=[validators.DataRequired()])
  description = core.StringField(widget=widgets.TextArea())
  data = simple.FileField(validators=[validators.DataRequired()])
```

**Comment by ChameleonRed** [comment]
`if not field.data or isinstance(field.data, string_types) and not field.data.strip():`
field.data = FieldStorage: FieldStorage(u'data', u'sesja.txt')

**Comment by crast** [comment]
well that's really weird.

I guess use InputRequired or come up with another validator to do the same
