### ISSUE TITLE
Handling Dates Before 1900

### ISSUE THREAD

**Issue by pawl** [wtforms/wtforms#218]
I know this one is a bit of an edge case, but I thought I would create an issue for it since there isn't one already.

In Python 2, strftime won't work on dates before 1900, which causes the DateTimeField to fail here on dates < 1900: https://github.com/wtforms/wtforms/blob/master/wtforms/fields/core.py#L733

It will work fine in Python 3.

Here's the full stack trace: https://gist.github.com/anonymous/2b822c602eeee29ed67b

**Comment by crast** [comment]
Have a proposed fix?

**Comment by ftm** [comment]
Closing this as it's been 4 years and Python 2 is reaching EOL. The author mentions that this is not an issue in Python 3.
