### ISSUE TITLE
Weird FieldList behavior

### ISSUE THREAD

**Issue by ramnes** [wtforms/wtforms#220]
At first I tried to use `FieldList` inside an other `FieldList`, and it just didn't work. So I started trying simpler things, and now I really don't understand `FieldList` anymore. 

Can someone explain me this?

```python
>>> from wtforms import Form, FieldList, StringField
>>> from wtforms.validators import InputRequired
>>> from werkzeug import MultiDict
>>> class Foo(Form):
...    bar = FieldList(StringField(), validators=[InputRequired()])
...
>>> # That one should work     
>>> f = Foo(MultiDict([("bar", ["qux"])]))
>>> # But actually... no
>>> f.validate()
False
>>> # And this is weird
>>> f.data
{'bar': []}
>>> # Let's try it an other way
>>> class Foo(Form):
...     bar = FieldList(StringField(validators=[InputRequired()]))
...     
>>> f = Foo(MultiDict([("bar", ["qux"])]))
>>> f.validate()
True
>>> # Looks good so far, let's try something bad
>>> f = Foo(MultiDict([("bar", 123)]))
>>> f.validate()
True
>>> # wait, wut?
```

**Comment by crast** [comment]
FieldList creates multiple values with different names inside.

Try rendering the form, you'll see.

Also, please limit this for bug tracking, not questions

**Comment by ramnes** [comment]
Okay so, I know what `FieldList` is meant for, and I don't think your answer help me at all. I was using WTForms for validating JSON input; rendering has nothing to do here.

I opened this issue because to my usage, this is definitely a bug, which in the end (and by the lack of any response), led me to use an other library: FieldList can't properly validate raw data like other fields.

**Comment by tangwz** [comment]
+1. FieldList is shit!
