### ISSUE TITLE
wtforms.ext.sqlalchemy should not be deprecated

### ISSUE THREAD

**Issue by hector** [wtforms/wtforms#221]
In `wtforms.ext.sqlalchemy` it can be found that:
```
warnings.warn(
    'wtforms.ext.sqlalchemy is deprecated, and will be removed in WTForms 3.0. '
    'Instead transition to the excellent WTForms-Alchemy package: '
    'https://github.com/kvesteri/wtforms-alchemy',
    DeprecationWarning
)
```

But WTForms-Alchemy documentation states ([link](https://wtforms-alchemy.readthedocs.org/en/latest/introduction.html#differences-with-wtforms-ext-sqlalchemy-model-form)):

> WTForms-Alchemy does not try to replace all the functionality of wtforms.ext.sqlalchemy. It only tries to replace the model_form function of wtforms.ext.sqlalchemy by a much better solution. Other functionality of .ext.sqlalchemy such as QuerySelectField and QuerySelectMultipleField can be used along with WTForms-Alchemy.

QuerySelectField and QuerySelectMultipleField functionality cannot be replaced with WTForms-Alchemy features. I suggest `wtforms.ext.sqlalchemy` is kept and the deprecation warning is erased.

**Comment by jdharms** [comment]
Also running into this warning.

**Comment by crast** [comment]
There is a replacement package that is a full extraction of `wtforms.ext.sqlachemy` at [`wtforms_sqlalchemy`](https://github.com/wtforms/wtforms-sqlalchemy)

I will update the docs to reflect that

**Comment by hector** [comment]
Thanks!
