### ISSUE TITLE
InputRequired validation fails with data/kwargs

### ISSUE THREAD

**Issue by Railslide** [wtforms/wtforms#230]
InputRequired validation fails when instantiating the form with keyword arguments. 

```
>>> class MyForm(Form):
            text = StringField(validators=[InputRequired()])
>>> form = MyForm(text='foo')
>>> form.validate()
False
>>> form.data
{'text': 'foo'}
```

Same result when explicitly passing data as param (i.e. `MyForm(data={'text':'foo'})`). It works as expected when using a MultiDict.

**Comment by crast** [comment]
InputRequired only validates that there is input from a form
