### ISSUE TITLE
Dynamic form handling

### ISSUE THREAD

**Issue by drahnr** [wtforms/wtforms#232]
How do i handle a dynamically expanded form.

Example:

* Each block is an entry form with a <kbd>remove</kbd> button (via jquery).
* The <kbd>add</kbd> button adds a new button (via jquery).
* The <kbd>submit</kbd> button sends a POST request to my flask application.

**How do I handle the resulting data posted to flask? How do I model this as a Form class?**

Ref: http://www.sanwebe.com/2013/03/addremove-input-fields-dynamically-with-jquery

**Comment by crast** [comment]
This isn't a support forum, this is for bug posts

Ask somewhere like http://stackoverflow.com
