### ISSUE TITLE
Handling GET requests

### ISSUE THREAD

**Issue by minimedj** [wtforms/wtforms#236]
Hi guys,

I am new guy to WTForm but I find it's concept is very robust and I widely use WTForm in my new project (with big success). It does great job handling all my POST requests.

Now I have to manage GET requests - basically I need to validate GET parameters to make sure that users send proper data. I found few libs that do validations, but I am wondering where it is possible to employ WTForm validation for this task?

Advantages:

1. No need for extra validation library
2. No need to learn new library
3. All validation is handled by one library (WTForm)

p.s. Maybe this functionality already exists?

**Comment by crast** [comment]
It sure does - you can pass django `request.GET` or werkzeug/flask `request.args` as formdata and it will "just work"  (except for one key exception, which is anything requiring a multipart form, such as file uploads)

**Comment by minimedj** [comment]
@crast Thank you for your reply!

For POST I use `form.validate_on_submit()`, what sould I use for GET?

p.s. I use Flask

**Comment by crast** [comment]
`request.args`
