### ISSUE TITLE
how can we install WTForm in odoo v9 in windows Environment

### ISSUE THREAD

**Issue by kartikdanidhariya** [wtforms/wtforms#237]
hi,
i install odoo v9 in windows environment 
after that i create one custom module in odoo v9 and i used wtform in that
but when i try in install that module in odoo v9 so it return error like
"import error : no module installed wtform"
after that i install wtform in my windows using "pip install WTForm"
and it install successfully after i check using "pip freeze" so it installed 
but it still return same error
so how can i solve this error
please help!!!

**Comment by crast** [comment]
This system is for reporting bugs, issues and feature requests. Support requests are better suited at community sites like either:

* http://serverfault.com/  for installation / server administration questions
* http://stackoverflow.com/ for coding / library usage questions

Also, this library is WTForms which is available with  `pip install WTForms`  (note the 's' on the end). There is also a WTForm library which is confusingly named but not related to ours.  So I'm not sure which one you are looking for, but in either case check one of the above sites for some help

**Comment by RichDijk** [comment]
I do have the same error.
