### ISSUE TITLE
Textarea misses the first line if empty

### ISSUE THREAD

**Issue by phoenixyjll** [wtforms/wtforms#238]
When saving a textarea with the first line empty (leading line break), the browser won't show that line after viewing the changed form, but the data sent to the server is correct. And then we save it again with nothing changed, data sent to the server also misses that line.

**Comment by crast** [comment]
Do you have an example of this?

I do not have a reproducible example of this

**Comment by phoenixyjll** [comment]
1. Create a TextAreaField, and render it in HTML.
2. Input something in the textarea with the first line empty. e.g. "\r\nabc".
3. Submit the form. The webpage is refreshed.
4. The first empty line misses in the textarea.

**Comment by davidism** [comment]
The HTML spec is surprisingly vague about this, but it looks like browsers strip an initial `\r\n`, and other frameworks account for this by adding one during rendering.
