### ISSUE TITLE
Error on documentation for custom validators

### ISSUE THREAD

**Issue by halcyonjuly7** [wtforms/wtforms#240]
http://wtforms.readthedocs.org/en/latest/validators.html#custom-validators

```python

class MyForm(Form):
    name = StringField('Name', [InputRequired()])

    def validate_name(form, field):
        if len(field.data) > 50:
            raise ValidationError('Name must be less than 50 characters')

```

`validate_name` is a class method which therefore needs `self` as it's first argument
or am I missing something?

**Comment by crast** [comment]
just rename `form` to `self`
