### ISSUE TITLE
Ignoring obj= value if global formdata is provided?

### ISSUE THREAD

**Issue by cnicodeme** [wtforms/wtforms#242]
Hi,

I'm trying to understand why my original field object is not used when the corresponding formdata field is not provided, and I don't understand.

Let's say I have a form (AccountForm) with two field : `display` and `email`.
I submit a POST request with only `display` (to update the name of the account user)

```
form = AccountForm(request.form, obj=original_account)
```

(original_account being the object from the database retrieved via SQLAlchemy).

Now, in my logical understanding world, I'd say that form will be : 

```
print form.display.data # = the value from form.request
print form.email.data # = The value from original_account, since form.request does NOT contains the key "email"
```

But it's not the case, `form.email.data` is empty!

The problem is coming from the file here https://github.com/wtforms/wtforms/blob/master/wtforms/fields/core.py#L286 

In order for my "logical understanding" to work, L285 - 286 should be removed, letting the formdata value by default, and reverting back to the `obj` parameter else, and increment L287 of one tab, to be placed under the `if` condition.

But before submitting a pull request, I'm pretty sure the issue is not coming from WTForms but from something on my end (something wrongly understood ?) ... but what am I missing?

Thank you for your indications.

**Comment by cnicodeme** [comment]
(Note, I said to remove L285-286, but increment tab of L287 too (to be placed under the `if` condition)).

**Comment by cnicodeme** [comment]
Ok I'm continuing to find the issue, and for a Field object, the `process_formdata` should work as expected (correctly), but for a `StringField`, the `process_formdata` transforms empty value (or absents) to an empty string (https://github.com/wtforms/wtforms/blob/master/wtforms/fields/core.py#L530)

Which override the default value of the `obj` when nothing is passed from the POST request, making the obj useless here, if I don't rewrite `StringField.process_formdata`.

If you have any advice here ... on my end, I'll continue to try to understand.

**Comment by crast** [comment]
It's a security concern to not have data get blanked out.
http://wtforms.readthedocs.org/en/latest/faq.html#why-does-blank-input-not-go-back-to-the-default-value

**Comment by alanhamlett** [comment]
@crast how is this a security issue?? This used to work but now pre-populating a form with an existing object is broken!

**Comment by alanhamlett** [comment]
[This example](https://wtforms.readthedocs.io/en/latest/crash_course.html#editing-existing-objects) no longer works. If the pre-existing object and the user input both get validated by the form, how can this be a security issue?
