### ISSUE TITLE
DateField Validate doesn't work correctly

### ISSUE THREAD

**Issue by nooperpudd** [wtforms/wtforms#245]
```python
class IMForm(Form):
    aaa = DateField("aaa",validators=[DataRequired(message="error")])


if __name__ == '__main__':

    b= {"aaa":"sfds"}
    form =IMForm(**b)
    if form.validate():
        print("validate")
    else:
        print(form.errors)
```
output:
```shell
validate
```
the date validator doesn't work.

**Comment by crast** [comment]
Not a bug. WTForms doesn't validate defaults... in other words fields passed via the keyword-arg constructor are expected to be valid already.

**Comment by nooperpudd** [comment]
@crast  what should I to do to validate the form values? 
why pass the keyword params should work?
