### ISSUE TITLE
Repeated BooleanField give incorrect results

### ISSUE THREAD

**Issue by PatriceBX** [wtforms/wtforms#246]
I have a form with a repeated BooleanField

```python
class MyForm(Form):
    selects = FieldList(BooleanField(), min_entries=5)     
```

If user has checked only one checkbox, for example the one with index 2, the POST only sends this field.   After doing:

```python
form = MyForm(request.form)
```

I get `form.selects.data = [True, False, False, False, False]`, so the order of the boolean fields has been lost, it is as though the one that was checked was the first.

It is not impossible to fix this, since 

```python
form.selects[0].id = 'selects-2'
```

So the information of which checkbox was checked is available.  It seems to me WTForms should do it when populating the form with the `request.form data`, and return form.selects as a list of `BooleanFields` with correct order.

**Comment by ripperdoc** [comment]
+1 on this. In general, FieldList ignores indices when populating the objects, which is strange to me. I made a hack around it, but would be great to see it fixed!

**Comment by davidism** [comment]
There's no guarantee that `selects-2` is actually the second item. A common pattern with `ListField` is to use JavaScript to add and remove items dynamically. In this case, a user could remove the first entry and add a sixth. The `min_entries` is still satisfied, but `selects-2` is now the first entry. This doesn't make much sense for `BooleanField`, but consider `StringField` or `FormField`.

A possible solution is to add a `sparse=True` argument. If `False`, it would assume empty fields for missing entries.

**Comment by azmeuk** [comment]
It seems to be the same discussion as #570 so I guess it is a wontfix?

**Comment by davidism** [comment]
Yeah, this is a shortcoming with HTML forms.
