### ISSUE TITLE
Looking for a tutorial for multi-step forms

### ISSUE THREAD

**Issue by rlam3** [wtforms/wtforms#250]
I'm looking for a way to do multiple page / step sign up.... I'm not sure how to do this with wtf forms. Or is there a better way of doing this type of signup process where I can get data from two different forms from two different pages?

ex:

signup/part1

get some more data
render next form
signup/part2

get some form data
redirect to /submit with data from part 1 and part 2
signup/submit

user verifies values and hits submit.
takes data from part 1 and part 2 and executes necessary code
redirects to another page

**Comment by crast** [comment]
There's many ways to implement this, perhaps even dozens of ways.

I don't know if it's a good idea to have WTForms' own documentation mention this; but maybe

**Comment by khanvuthy** [comment]
Yes I have the same wonder too, I don't know how can we get value from WTForm with multi step.
I already search with many time but still can't found the solution.

**Comment by snowch** [comment]
If there are dozens of ways to implement this, new wtforms users will get even more confused due to the choices they have to make. +1 for this documentation using the most typical implementation approach.

**Comment by khoitsma** [comment]
I didn't see an answer to this request yet.  Am I missing something?

**Comment by davidism** [comment]
Process form 1 on page 1: if it's valid, put the data in the session and redirect to page 2, etc. On the last page, use all the data from the session to do what you need to do.
