### ISSUE TITLE
For IntegerField or FloatField when required the 0 should be an accepted value.

### ISSUE THREAD

**Issue by lipis** [wtforms/wtforms#255]
and not allowing the empty value `''` but the 0 should be a valid number..

**Comment by lipis** [comment]
@crast Why exactly is this invalid?!

```python
class MyForm(wtf.Form):
  amount = wtforms.FloatField('Amount', [wtforms.validators.required()])
  count = wtforms.IntegerField('Count', [wtforms.validators.required()])
```

In the above form, I can add any value to the `amount` and `count` except `0` or `None`.. which is a bit strange because `0` is perfectly accepted input when `required` and `None` should be not allowed.. since it's not a number.

If I have these field `optional` then of course 0 is allowed.. but it also accepts the empty string (or None) which is not a number and I'll have to do an extra action in order to validate it (even though I'm asking for Integer or Float)

**Comment by lipis** [comment]
@crast ?!

**Comment by NixonInnes** [comment]
I get this issue too. Why is "0" not a valid value for FloatField and IntegerField when the validator DataRequired is applied?

**Comment by lipis** [comment]
@NixonInnes That is exactly my point :D `None` or `` or any non numerical string should be forbidden.. not `0` :)

**Comment by georgekis** [comment]
+1 keep up

**Comment by NixonInnes** [comment]
I've found a somewhat workaround, if you set the default value to 0.0 in the model and don't use any validators on the form definition; it will accept 0, and still error on "Not a valid float value".

**Comment by crast** [comment]
@lipis this is a well-documented issue with the "required" validator,  there's two paragraphs of notes on it:  http://wtforms.readthedocs.org/en/2.1/validators.html#wtforms.validators.DataRequired

For back-compatibility reasons, we cannot change the behaviour of the "required"/"data_required" validator in the 2.x series, because it would be a breaking change and that is a violation of semantic versioning policy.

We do have another validator called [InputRequired](http://wtforms.readthedocs.org/en/2.1/validators.html#wtforms.validators.InputRequired) which works for integer 0 and float 0.0 because it checks the form input is specified, not the value truthiness.

[WTForms 3.0](https://github.com/wtforms/wtforms/issues/154) is a pretty hefty re-design and it addresses many common issues, and will address the "required" issue.

I'm reopening this and setting the milestone as 3.0 so that it's tracked

**Comment by lipis** [comment]
Thanks @crast for clearing this up.

**Comment by RazerM** [comment]
> We do have another validator called [InputRequired](http://wtforms.readthedocs.org/en/2.1/validators.html#wtforms.validators.InputRequired) which works for integer 0 and float 0.0 because it checks the form input is specified, not the value truthiness.

What changed?

```python
from wtforms import Form, IntegerField, FloatField
from wtforms.validators import InputRequired

class MyForm(Form):
    amount = FloatField('Amount', validators=[InputRequired()])
    count = IntegerField('count', validators=[InputRequired()])

form = MyForm()
form.process(amount='0', count='0')
form.validate()
print(form.errors)
```

```
{'amount': ['This field is required.'], 'count': ['This field is required.']}
```

**Comment by RazerM** [comment]
My minimal example doesn't reflect the way the form is instantiated in my real application. I had default values in my client-side form that were not strings and Flask-WTF will pass `request.get_json()` as `formdata`.

While investigating this, I did find that validation fails when using data, kwargs, or obj with zeros:

```python
from werkzeug.datastructures import ImmutableMultiDict
from wtforms import Form, IntegerField, FloatField
from wtforms.validators import InputRequired


class MyForm(Form):
    amount = FloatField('Amount', validators=[InputRequired()])
    count = IntegerField('Count', validators=[InputRequired()])


class MyObject:
    def __init__(self, *, amount, count):
        self.amount = amount
        self.count = count


def process(*args, **kwargs):
    form = MyForm(*args, **kwargs)
    form.validate()
    print(form.errors)


# Normal POST data
process(ImmutableMultiDict(dict(amount='0', count='0')))  # ✅
# Flask-WTF will call request.get_json()
process(ImmutableMultiDict(dict(amount=0, count=0)))  # ✅
print()

# Documentation states these should already be coerced, but it fails validation
process(data=dict(amount=0, count=0))  # ❌
process(amount=0, count=0)  # ❌
process(obj=MyObject(amount=0, count=0))  # ❌
print()

# For completeness, these also fail (as documented).
process(data=dict(amount='0', count='0'))  # ✅
process(amount='0', count='0')  # ✅
process(obj=MyObject(amount='0', count='0'))  # ✅
```

```
{}
{'amount': ['This field is required.'], 'count': ['This field is required.']}

{'amount': ['This field is required.'], 'count': ['This field is required.']}
{'amount': ['This field is required.'], 'count': ['This field is required.']}
{'amount': ['This field is required.'], 'count': ['This field is required.']}

{'amount': ['This field is required.'], 'count': ['This field is required.']}
{'amount': ['This field is required.'], 'count': ['This field is required.']}
{'amount': ['This field is required.'], 'count': ['This field is required.']}
```

**Comment by adrian410** [comment]
Up

**Comment by adrian410** [comment]
Suggestion :

Replace : 
`if not field.raw_data or not field.raw_data[0]:`

with : 
`if not field.raw_data or field.raw_data[0] is None:`

at

https://github.com/wtforms/wtforms/blob/master/src/wtforms/validators.py#301

**Comment by lipis** [comment]
@adrian410 Maybe submit a PR with this change instead, since this issue is closed.

**Comment by adrian410** [comment]
Well it's the first time I try to do a PR. And I get a 403.
Trying to do a PR on master => 403
Creating a new branch => 403

**Comment by adrian410** [comment]
If somebody can to do the PR request or show me the right steps to do it, I would be really thankfull.

**Comment by lipis** [comment]
What happens when you try to click the edit button from here:

https://github.com/wtforms/wtforms/blob/master/src/wtforms/validators.py

<img width="394" alt="Screenshot 2019-11-28 at 3 29 28 PM" src="https://user-images.githubusercontent.com/125676/69814187-f1d1b900-11f3-11ea-8a19-bbfdf398ea37.png">

**Comment by adrian410** [comment]
Great it worked, Thanks ! :)
