### ISSUE TITLE
Keep order and number of entries in list of FieldList errors

### ISSUE THREAD

**Issue by the-tosh** [wtforms/wtforms#257]
Hi. I use WTForms 2.1.0 and I'd like to discuss [this issue](https://github.com/wtforms/wtforms/issues/49) one more time.

In modern SPA applications where backend usually don't render any forms it's sometimes difficult or just inconvenient to validate each field separately as you offered in above-mentioned topic. Also, why someone should do it if form.validate() can validate all fields correctly? All but FieldList.

So, I guess it would be great if FieldList returned as many error objects as it received entries if there's at least one error. Otherwise, it should return empty list as usual.

This patch is already available in my fork, but I'll try to attach commit here (github UI sometimes is not obvious to me).

**UPD**: Here is the pull request. #258

**Comment by davidism** [comment]
Closed by #407
