### ISSUE TITLE
Float fields don't accept 0 as a value when used with the DataRequired() validator

### ISSUE THREAD

**Issue by NixonInnes** [wtforms/wtforms#260]
When a FloatField or IntegerField is defined with the DataRequired() validator, the form will not accept 0, or 0.0 as a valid entry. 
DataRequired() implies that an input is required in the form, and in many cases 0 would be a valid answer (i.e co-ordinates).

**Comment by lipis** [comment]
#255

**Comment by crast** [comment]
Closed as duplicate of #255
