### ISSUE TITLE
no new form defaults when request.form exists

### ISSUE THREAD

**Issue by portermahoney** [wtforms/wtforms#267]
I'd like to use post data in a view and also create a new form.  But when there is something in request.form the defaults for the new form are not displayed because of this [design decision](https://wtforms.readthedocs.org/en/latest/faq.html#why-does-blank-input-not-go-back-to-the-default-value).  

I could pass an empty formdata (TestForm(formdata = None)) but that seems hacky, i'd rather get a suggestion on how to change the approach.

```
def test_view:
    rows = json.loads(request.form['rows'])
    form = TestForm()
...

class TestForm(Form):
        test = StringField('Test', default = 'test')

```

Similar to this [issue](https://github.com/wtforms/wtforms/issues/119) but the data is posted to this view from another and all I want to do is create the form based on some of this post data, the resulting form could even be submitted to a different view to avoid having to work out which form submitted the view.  I wanted to use post instead of get because the data could be > 2000 chars.  

Thanks!

**Comment by davidism** [comment]
This is a Flask-WTF behavior.  Passing `None` is correct.

**Comment by alanhamlett** [comment]
Related to #242.
