### ISSUE TITLE
How to Set FileFieldRequired?

### ISSUE THREAD

**Issue by Siecje** [wtforms/wtforms#269]
I'm using Flask with a WTForm with a FileField.

I can't seem to make the FileField required and still be able to upload a file.

I also tried to create a validator method but field.data is an empty string.

What is the correct way to set a FileField is required?

I also tried `validators.InputRequired()` and `validators.DataRequired()`
https://github.com/wtforms/wtforms/issues/211

``` Python
from wtforms import BooleanField, FileField, Form, TextField, validators

class RipJobForm(Form):
    rip_file = FileField("Import File", [validators.Required()]) # Says required even if file specified.

    def validate_rip_file(self, field):
        if field.data: # '' even if file is specified
            return True
        raise validators.ValidationError("Required.")

# View

@app.route("/upload/", methods=["GET", "POST"])
def upload_rip_file():
    form = RipJobForm(request.form)
    if request.method == "POST":
        if form.validate():
            rip_file = request.files[form.rip_file.name]
            fileName = secure_filename(rip_file.filename)
            filePath = os.path.join(LOCAL_DROP_DIR, fileName)
            rip_file.save(filePath)
            # ...



# Template

  <form method="POST" action="{{ url_for("upload_rip_file") }}" enctype="multipart/form-data">
    {{ form.csrf_token }}
    {{ wtf.form_field(form.rip_file) }}
    {{ wtf.form_field(form.server1) }}
    {{ wtf.form_field(form.server2) }}

    <button type="submit" class="btn btn-default">Upload</button>
  </form>
```

**Comment by davidism** [comment]
`request.files` contains the uploaded files.  See how Flask-WTF handles it: https://github.com/lepture/flask-wtf/blob/v0.12/flask_wtf/form.py#L74-L77.

**Comment by homeworkprod** [comment]
I just wasted an uncomfortable amount of time tracking this down and finally ending up here :(

Side note: That code subclasses `SecureForm` which has been dropped from WTForms in https://github.com/wtforms/wtforms/commit/c49ecfb7e76f919eafb5c6a11c3b795c4e613757#diff-1f7c3cbe9e3233680a75ba59c0b46f6d (I'm sure you know that, @davidism, but for the record).
