### ISSUE TITLE
Ability to populate_obj for a specific fields in a model

### ISSUE THREAD

**Issue by robertlagrant** [wtforms/wtforms#271]
I have a model A that has related model B, where model A can have multiple related Bs.

I have a form that allows the user to update A, but not the related Bs. Those are handled elsewhere.

When I do a populate_obj from the form data on A, and persist it in SQLAlchemy, A's relationships with its Bs are gone. Is it possible to select the fields to move across in populate_obj?

**Comment by davidism** [comment]
I'm not sure how this is happening, if you're not assigning to the relationship then nothing about it should change. `populate_obj` can be overridden to work however you want, there's no particular customization for it.
