### ISSUE TITLE
Add documentation for HTML5 fields

### ISSUE THREAD

**Issue by ben4ever** [wtforms/wtforms#275]
I understand that it might be quite a bit of work to document the HTML5 fields in the `wtforms.fields.html5` module, but it would be great if the function docstrings in this module would be used to generate a basic documentation through Sphinx.
That would be a great start and would raise awareness to people that WTForms even provides HTML5 fields :smiley:.

**Comment by cmcaine** [comment]
I got as far as cloning the repo and modifying the widgets and fields in core before I realised that there are html5 variants available.

I don't understand why they're not already used in place of the core ones, though. Browsers should fall back to something sensible if they don't understand type=date or similar.

**Comment by Deathnerd** [comment]
I'm willing to do this, but I'm a bit confused on what you want the end result to be? It looks as if there are already basic docstrings for the classes themselves that specify the type of elements the fields produce. Are you perhaps referring to the actual documentation under the `docs` directory?

**Comment by ben4ever** [comment]
> Are you perhaps referring to the actual documentation under the `docs` directory?

Yeah, that's right. Just to make it known to people who read the documentation that there actually are HTML5 fields.

**Comment by cmcaine** [comment]
It's what I meant too: there's no mention on [readthedocs](https://wtforms.readthedocs.io/en/latest/fields.html#basic-fields) of any of the html5 fields.

They're also not imported by default if you `import wtforms.fields`. You have to know they're there and explicitly `import wtforms.fields.html5`

That makes them hard to discover.

**Comment by Deathnerd** [comment]
Okay, I've added the HTML5 fields to the docs under the Basic Fields section and before the Convenience Fields section. Half of me thinks that they should be included under Convenience fields and the other half thinks they should be as I have them right now. I'll let the community and contributors decide though

**Comment by cmcaine** [comment]
Where it is now looks good enough to me. Thanks :)

Might be worth mentioning briefly why they're a good thing (mobile OSs providing custom keyboards).

**Comment by Deathnerd** [comment]
Good point. There's a few formatting issues I need to fix tomorrow, so I'll throw those in there as well

**Comment by ftm** [comment]
This has been fixed in #326 and #409

**Comment by Deathnerd** [comment]
Thanks everyone for picking up where I dropped the ball. Things got complicated in life real quick around that time
