### ISSUE TITLE
Passing FieldList data in kwargs to form.process fails

### ISSUE THREAD

**Issue by acgs** [wtforms/wtforms#277]
I recently was working with a form with a FieldList field, and found what seems to be a bug in the process function. I am using CherryPy, and the POST arguments come in a kwargs to my http endpoint. Due to this and my need to dynamically add choices to some choice fields, I need to pass the kwargs to the form.process function. However, it looks like the algorithm for applying data in kwargs doesn't work very well for FieldList fields.

In particular, I have a FieldList called aliases, with a min number of 3. I get back keys "aliases-0", "aliases-1", and "aliases-2" in my kwargs, and they have appropriate data in them. I pass my kwargs to the form as form.process(**kwargs), but when pulling the data out using form.data, aliases is a list of nulls:
form.data['aliases'] == [null, null, null].

To make this work, I iterate over the aliases in kwargs first, put them into an array, and place that back in kwargs with the key 'aliases' - then the array properly maps to the aliases FieldList.

After looking at the source, it looks like the problem is with the algorithm for pulling data out of kwargs - it looks for a key in kwargs with the name of the field (in my instance, "aliases"), and if it finds it, then it passes it on to the field.process. However, the keys in my kwargs are all suffixed with "-0", "-1", etc., so of course it won't find the key "aliases" in kwargs.

So, my question really is: is this working as intended and I have to map these inputs to an array manually, am I using the API wrong, or is this actually a bug?

Thank you,
Victor Szczepanski

**Comment by azmeuk** [comment]
Feels related to #509.
