### ISSUE TITLE
validators.NumberRange renders error if parameter "message" contains "%"

### ISSUE THREAD

**Issue by itnow** [wtforms/wtforms#283]
Using a percent sign in error message:

```
    bonus = IntegerField('Bonus %', validators=[NumberRange(0, 100, 'from 0% to 100%')])
```

produces a error: "unsupported format character"

![scr](https://cloud.githubusercontent.com/assets/1656651/16340139/1ef06c88-3a2f-11e6-98d8-9f9320f24dfd.png)

So maybe we need some smart escaping for message parameter string?
Or maybe place some note about this limitation in Docs?

**Comment by roganov** [comment]
Just escape `%` with `%%`.

**Comment by ftm** [comment]
As @roganov says you just need to escape the `%`
