### ISSUE TITLE
SelectField should not coerce None into string "None"

### ISSUE THREAD

**Issue by georgschoelly** [wtforms/wtforms#289]
I've stumbled upon weird behavior where a SelectField could have the value `"None"` instead of one of the choices and [I'm not the only one having encountered this](http://stackoverflow.com/q/35460282). Example:

```
import wtforms
class MyForm(wtforms.Form):
    select_field = wtforms.SelectField(choices=[("a", "A"), ("b", "B")])

form = MyForm()
print(form.select_field.data)
print(type(form.select_field.data))
```

which results in:

```
None
<class 'str'>
```

What happened? `SelectField` coerced the field's default  value `None` to `"None"`. I would expect it to be `None`.

Additionally to unexpected, this is inconsistent with other types. E.g. `SelectField(coerce=int)` gives `None` as expected.
## Details

The relevant code is in [`fields/core.py`](https://github.com/wtforms/wtforms/blob/cbf70af6d1a851500d7c09a03853a7d60d68be42/wtforms/fields/core.py#L457):

```
# get's called with value=the_default_value which can be None
def process_data(self, value):
    try:
        self.data = self.coerce(value)
    except (ValueError, TypeError):
        self.data = None
```

Strangely, this behavior is [documented by one of the tests](https://github.com/wtforms/wtforms/blob/78ba1d6f571f1c89ee7c7732a8d64a36110699d1/tests/fields.py#L290):

```
self.assertEqual(form.a.data, 'None')
```

The commit adding the test 880e98a39675bb3725be8321a93b66e62a3f3f80 does not explain why this behavior would be correct. Additionally, another test f6d8c75e200ae26a9ce4186868d8fdf5c3342646 kinda relies on this behavior, but looking at it, I would not say that this is correct behavior. (Namely, `bool("None") -> True` instead of `bool(None) -> False`.
## Proposed fix

First of all, this would change the API slightly, but I don't think this is a problem. As it currently stands, its a bug that is not obvious. `None` and `"None"` look exactly the same when printing them, but because `bool(None) != bool("None")` this easily lead to unexpected behavior.

My proposed fix tests for `None`, but we could also use `default=unset_value` instead of `default=None` in the constructor and test for that. Or alternatively, instead of using `str` as the default coercion, we could use an identity function that raises if the value is not a string already.

The changes are in pull request #288.

**Comment by fchennouf** [comment]
Same Issue, i add optional validators to my SelectField, so i received a None type value and it's coerced to 'None' string Value. Which is a nonsense. We cannot know anymore whether a value has been introduced unless we check again with choices.

**Comment by samuelhwilliams** [comment]
Same here.

I tried to use a `DataRequired` validator with a custom error message. This coercion on None to string "None" blocks the custom error message from being applied.

InputRequired works fine, so I'm using that now (and arguably should have been from the start), but it still feels like using DataRequired shouldn't be a problem.

**Comment by calumah** [comment]
Hi, same here too

SelectField + Optionnal() validator + do not add this `<input>` in your html page (missing GET/POST data) = form.input.data give 'None' as string

Simple workaround is to set `default=''` and `form.input.data` give real None type but this is not obvious....

See also:

- another issue : #324 
- PR : #288  
- External : https://stackoverflow.com/questions/35460282/flask-wtf-dynamic-select-field-gives-none-as-a-string

**Comment by georgschoelly** [comment]
Pull request #288 was just merged.

**Comment by alswl** [comment]
Any plan to update pypi version? @georgschoelly

**Comment by JerPatton** [comment]
Had this behaviour been rolled back or is there a reason why I still get the wrong conversion of None to 'None' with version 3.0.1 ?
I tried to provide a `default=None ` parameter to SelectField or any other suggested solutions in linked issues/posts, but without any success so far.
