### ISSUE TITLE
DecimalField should have correspond DecimalRange Validator

### ISSUE THREAD

**Issue by banxi1988** [wtforms/wtforms#293]
When we use NumberRange as an validator,it will cause some bug.
like:  Decimal(0.02) < 0.02  , a Decimal object will less than it's float like number.
and that easily cause some bug, so we need DecimalRange which use Decimal as min or max property

**Comment by davidism** [comment]
`NumberRange(min=Decimal('0.2'))`

**Comment by banxi1988** [comment]
@davidism Thanks. it works,while I'm still add a custom valiator class DecimalRange for my self.
so that I don't need to import Decimal class all the time.
