### ISSUE TITLE
When none of the radio buttons of a RadioField are selected. The InputRequired validator, adds an error message to the form, but it is not rendered by the template engine. Also, the label for the RadioField is not shown.

### ISSUE THREAD

**Issue by SireMartin** [wtforms/wtforms#295]

**Comment by davidism** [comment]
WTForms does not have a template engine that renders errors.  Are you confusing this with a helper library such as Flask-Bootstrap?

**Comment by SireMartin** [comment]
I did not mention me also using flask bootstrap so the error must be there
i suppose. Thanks for the hint!
Maarten
