### ISSUE TITLE
Do not escape HTMLStrings in SelectField choices

### ISSUE THREAD

**Issue by sonovice** [wtforms/wtforms#301]
If choices are passed to `SelectField` as `HTMLString`, the content should not be escaped.

### Example
```python
from wtforms.widgets.core import HTMLString

languages = [('en', HTMLString('<i class="en flag"></i>English')),
             ('de', HTMLString('<i class="de flag"></i>Deutsch'))]
[...]
pref_language = SelectField(choices=languages)
```

### Possible solution
Instead of simply using `escape(...)` from `html` (like for example [here](https://github.com/wtforms/wtforms/blob/master/wtforms/widgets/core.py#L313)), use something like this:
```python
from html import escape

def escape_html(text_string):
    if hasattr(text_string, '__html__'):
        text_string = text_string.__html__()
    else:
        text_string = escape(text_string)
    return text_string
```

**Comment by sonovice** [comment]
For some reason it still does not work in my project. Did I overlook a piece of code somewhere that would still escape my strings?

**Comment by davidism** [comment]
You'll need to install the dev version of wtforms until a new release is made.  There is no schedule for a new release at this time.

**Comment by sonovice** [comment]
I guess the problem is with flask-wtf. Since it's not compatible with wtforms >= 3.0, I have to work out something else... Thanks anyways, maybe this will come in handy sometime later.
