### ISSUE TITLE
Label text isn't HTML-escaped

### ISSUE THREAD

**Issue by craigholm** [wtforms/wtforms#315]
When a label is rendered, the contents of the label element aren't escaped either with `__str__` or `__html__`.

```python
>>> from wtforms import IntegerField, Form
>>> class MyForm(Form):
	foo = IntegerField('Number (must be < 10):', default=0)

	
>>> form = MyForm()
>>> for field in form: print(field.label)

<label for="foo">Number (must be < 10):</label>
>>> for field in form: print(field.label.__html__())

<label for="foo">Number (must be < 10):</label>
```

**Comment by andreagrandi** [comment]
Snyk vulnerability scanner reports WTForms 2.1 as vulnerable https://snyk.io/vuln/SNYK-PYTHON-WTFORMS-40581

Would it be possible to acknowledge this issue in some way? I know 3.0 is in development but even for this reason it would be nice to know if the new version will be affected as well.

Thank you so much, cheers

**Comment by davidism** [comment]
There should be very few circumstances where it makes sense to put untrusted input into a label, that's just not what labels are for. Reporting this as an XSS is misleading.

**Comment by jace** [comment]
I urge you to reconsider this decision. Our internal assumption has grown to be that all text will be escaped unless explicitly marked as HTML. After nearly a decade of peaceful life like this, this one place has popped up as an exception to the general rule.

Now we have to audit for every use of `ListWidget`, plus leave a warning in each place for the next time someone touches that line. Or just fork `ListWidget` so it behaves likes everywhere else.

**Comment by rfkortekaas** [comment]
I'm facing an issue due to the change of this. I try to use HTML special chars in the field label:

### Actual Behavior

```python
>>> import wtforms
>>> class F(wtforms.Form):
...     foo = wtforms.IntegerField('&epsilon;')
>>> f = F()
>>> for field in F: print(field.label)

<label for="foo">&amp;epsilon;</label>
```

### Expected Behavior

```python
>>> import wtforms
>>> class F(wtforms.Form):
...     foo = wtforms.IntegerField('&epsilon;')
>>> f = F()
>>> for field in F: print(field.label)

<label for="foo">&epsilon;</label>
```

### Environment

* Python version: 3.7.4
* wtforms version: 2.3.1

Furthermore I really don't understand why this is a possible source for XSS as there is no user-input affecting the field label. E.g. the source of the label originates from the developer and when he has bad intentions you cannot prevent it like this.

**Comment by eliteuser26** [comment]
Similar to the previous comment, in version 2.2.1 I was able to use html code in the label text. However in version 2.3.1 it doesn't work anymore. How can I break a text over 2 lines if it is being parsed before rendering. It is for the developer to decide if he should use html code or not. Is there any other option that is not documented in WTForms that would do the same thing.

**Comment by rfkortekaas** [comment]
I found a solution for this. Maybe it's useful to add it to the documentation.

For escaping WTForms uses `escape` from MarkupSafe. You can pass an Markup object to the escape function to be able to format HTML.
```python
>>> import wtforms
>>> from markupsafe import Markup
>>> class F(wtforms.Form):
...     foo = wtforms.IntegerField(Markup('&epsilon;'))
>>> f = F()
>>> for field in f: print(field.label)

<label for="foo">&epsilon;</label>
```

**Comment by sovankiry** [comment]
> I found a solution for this. Maybe it's useful to add it to the documentation.
> 
> For escaping WTForms uses `escape` from MarkupSafe. You can pass an Markup object to the escape function to be able to format HTML.
> 
> ```python
> >>> import wtforms
> >>> from markupsafe import Markup
> >>> class F(wtforms.Form):
> ...     foo = wtforms.IntegerField(Markup('&epsilon;'))
> >>> f = F()
> >>> for field in f: print(field.label)
> 
> <label for="foo">&epsilon;</label>
> ```

@rfkortekaas  Thank you so much for your solution and it is working for me. I've problems when upgrade WTForm to version 2.3.x from my old version.
