### ISSUE TITLE
How about process field data before access?

### ISSUE THREAD

**Issue by protream** [wtforms/wtforms#316]
Every field can define a `process` function, just like `validate`, used like this:

```
name = StringField()

def process_name(self, field):
    return field.data.capitalize()
```

So, when user input `foo`, we get `Foo`.

**Comment by crast** [comment]
That's confusing because it does something different from the [process_* methods](http://wtforms.readthedocs.io/en/2.1/fields.html#wtforms.fields.Field.process) and also basically does what [filters](http://wtforms.readthedocs.io/en/2.1/fields.html#wtforms.fields.Field.__init__) already do
