### ISSUE TITLE
IntegerField raises an exception if None sent

### ISSUE THREAD

**Issue by fchennouf** [wtforms/wtforms#318]
Hello,

I have a problem with IntegerField when None is sent as a value, it raises an exception in process_formdata
>def process_formdata(self, valuelist):
>        if valuelist:
>            try:
>               self.data = int(valuelist[0])
E               TypeError: int() argument must be a string or a number, not 'NoneType'

In addition to valuelist, we should check the 0 value if its not None before using it to avoid this problem.

**Comment by davidism** [comment]
This is part of a more general cleanup I want to do with field processing behaving consistently.

**Comment by ergo** [comment]
Any news on this? I'm also hitting this bug right now.

**Comment by iteratelance** [comment]
Yes, same issue if the value is null.

I think that the solution should be to check for a TypeError as well as a ValueError

```python
    def process_formdata(self, valuelist):
        if valuelist:
            try:
                self.data = int(valuelist[0])
            except ValueError:
                self.data = None
                raise ValueError(self.gettext('Not a valid integer value'))
            except TypeError:
                self.data = None
                raise ValueError(self.gettext('Not a valid integer value'))
```

**Comment by davidism** [comment]
Lookingy at this again, I'm not clear how you're managing to send None, formdata should be strings only.

**Comment by ergo** [comment]
@davidism This can happen when someone for example validates JSON payloads with wtforms I think.

**Comment by davidism** [comment]
We don't support JSON (yet). The fact that it works in some cases is an accident. We are working on larger design questions for supporting other data sources besides form data.

**Comment by ergo** [comment]
Sure, that makes sense and it would obviously break for nested data structures, `SomeForm(foo=bar, **kwargs)` is established WTForms API and user might pass there something else than string by accident or on purpose like with `SomeForm(bar=request.params.get('bar'))`.
