### ISSUE TITLE
field for timezone selection

### ISSUE THREAD

**Issue by thestick613** [wtforms/wtforms#322]
This could have some usage. I'm going to use a country selector and derive the timezone from that, but it's not ideal.

**Comment by pferreir** [comment]
How do you derive the timezone from a country such as the US? In my experience, it's best to use a `SelectField` with `choices` extracted from `pytz`. [Here](https://github.com/indico/indico/blob/master/indico/web/forms/fields/datetime.py#L250)'s a possible approach.

**Comment by ftm** [comment]
I'm going to close this because as @pferreir says its just a `SelectField` with choices that can be easily extracted.
