### ISSUE TITLE
Default SelectField value is `u'None'`

### ISSUE THREAD

**Issue by pferreir** [wtforms/wtforms#324]
In the definition of `SelectField`, data is being coerced [to `text_type` by default](https://github.com/wtforms/wtforms/blob/2.1/wtforms/fields/core.py#L445). That causes the default value of the field [to be `u'None'`](https://github.com/wtforms/wtforms/blob/2.1/wtforms/fields/core.py#L463). I've ended up having to use `coerce=lambda x: x or None` in my field definition. Maybe that should actually be the default?

**Comment by collisdigital** [comment]
Related: https://github.com/wtforms/wtforms/pull/288 ?

**Comment by georgschoelly** [comment]
#288 just got merged, this probably solves this issue.

**Comment by ftm** [comment]
I'm going to close this issue since #288 was merged
