### ISSUE TITLE
FloatField should accept comma as decimal separator

### ISSUE THREAD

**Issue by mpianka** [wtforms/wtforms#328]
just convert "," to "." on assign. half of the world uses comma.

**Comment by kblomqvist** [comment]
I think this should be done on some localization layer instead.

Workaround:
```python
number = FloatField('Number', filters=[lambda x: x.replace(',', '.')])
```

**Comment by ftm** [comment]
As @kblomqvist pointed out this can be handled using filters. I would be hesitant to include something like this in the library as it depends on locale and using a comma as a separator isn't technically a valid floating point number by most definitions.

**Comment by abogaard** [comment]
using 2.2.1 this workaround doesnt seem to apply for float fields or decimal fields. perhaps it's trying to cast the input as a float / decimal before applying the filter?

**Comment by abogaard** [comment]
Could it be that processform runs before the filter operation? Using version 2.2.1 I cannot get the filter option above to work in either DecimalField or FloatField
