### ISSUE TITLE
Neutral value in SelectField

### ISSUE THREAD

**Issue by lusy** [wtforms/wtforms#335]
Hey, I'd like my SelectFields to have a neutral value (e.g. to allow users to select "none" out of a list of countries or similar). As far as I can see, the current implementation of the SelectFields in wtforms doesn't bring this out of the box, so the way to go would be to put an additional value in the choices list. Am I correct? Or did I miss something? Thanks.

**Comment by ftm** [comment]
You would have to add a "None" option yourself. Since this doesn't really involve any special behaviour on the part of the library this isn't something we're planning on implementing
