### ISSUE TITLE
Wrong Email validation 

### ISSUE THREAD

**Issue by FadhelC** [wtforms/wtforms#336]
There's an edge case where a wrong email address validates:
`foo@bar@baz.com` passes validation where it should't.
Only a single "**at sign**" should be present in an email address.

I would suggest the use of the following regular expression (derived from [RFC 5322](https://www.ietf.org/rfc/rfc5322.txt)) as the email validation regex:
 `r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"`

**Comment by davidism** [comment]
closed by #294
