### ISSUE TITLE
Using a generator for a SelectField's choices

### ISSUE THREAD

**Issue by WilliamMayor** [wtforms/wtforms#339]
In order to speed up my page loads I converted some SelectField choices attributes to generators. These generators pull data from the database, and so can be slow sometimes. There are occasions where the choices never need to be rendered, so loading them every time is wasteful.

If the choices *are* rendered in a page, everything works beautifully. If that page is submitted but the form doesn't validate, then the select field no longer shows all of the options. Instead it shows the options from the one after the selected option onward.

e.g. If the choices are `[1, 2, 3, 4, 5]` and the user has selected 3 but made an error elsewhere in the page. The page will render the errors but only show `[4, 5]` in the select field.

Looking through the code, I think it's because the select field's `pre_validate` method iterates through the generator until it finds a matching value, then it breaks. When the page is rendered the generator continues from where it left off.

I think my use case might be a little unusual, so I'm not sure if a fix in WTForms is a good idea. However, using a generator for your choices also seems like a perfectly normal Pythonic thing to do, so I thought I'd raise it.

**Comment by WilliamMayor** [comment]
Sorry to pester, any thoughts on this?

I don't know whether to address in this in my code, or work on a PR for WTForms? What the best course of action?

**Comment by davidism** [comment]
Don't use generators for choices. Generators are not reusable, form fields are.

**Comment by WilliamMayor** [comment]
Wow, thanks?
