### ISSUE TITLE
DecimalField default is not working

### ISSUE THREAD

**Issue by matdrapeau** [wtforms/wtforms#354]
When using default value into a DecimalField during validation, a ValueError of "Not a valid decimal value" is returned even if the default is a valid decimal.

**Comment by davidism** [comment]
Please add a reproducible example.

**Comment by matdrapeau** [comment]
`DecimalField(default=0)`

when `validate_on_submit` with an empty string, it returns the error

**Comment by matdrapeau** [comment]
Also tried this without success:
`DecimalField(default=None, validators=[Optional])`

**Comment by davidism** [comment]
An empty string isn't a valid integer. The default is only applied when there is *no* form data provided. This is by design. Unrelated, the validator needs to be instantiated: `Optional()`.
