### ISSUE TITLE
Multiple tables data into single table

### ISSUE THREAD

**Issue by umardraz** [wtforms/wtforms#359]
Hello how I can pass multiple object to WTform.

Here is my Form

```
class SettingsForm(FlaskForm):
    name = StringField('Full Name', validators=[DataRequired()])
    user_name = StringField('Username', validators=[DataRequired(), Email()])
    password = PasswordField('Password')
    site_title = StringField('Site title', validators=[DataRequired()])
    login_heading = StringField('Login page heading', validators=[DataRequired()])
    logo = FileField('Logo', validators=[
        FileAllowed(['jpg', 'png', 'gif'], 'Images allowed only!')
    ])
    background = FileField('Login Page background', validators=[
        FileAllowed(['jpg', 'png', 'gif'], 'Images allowed only!')
    ])
    submit = SubmitField('Update Settings')
```

I have 2 tables (users and settings)

name, user_name and password fields are in users table 

And the rest of the fields are in settings table.

Now if I do this

`form = SettingsForm(obj=get_settings())
`
Then site_title, login_heading, logo and background fields filled with data successfully

Now how I can pass users's table data to SettingsForm along Settings's table. I had tried this

`form = SettingsForm(obj=user.get_user(current_user.id))
`
But this remove settings tables's value from table.

**Comment by davidism** [comment]
You'll need to manually create an object with all desired attributes if you want to use it this way. It would make more sense to use two different forms with prefixes.
