### ISSUE TITLE
Add a Field kwarg attribute to allow processing of reserved-name request parameter

### ISSUE THREAD

**Issue by pzingg** [wtforms/wtforms#36]
You cannot use Python- or wtforms-reserved names for Fields.  This limits wtforms' ability to work with pre-exisiting libraries and APIs.  For example, the Google App Engine's Users API has a function called create_login_url.  It adds a destination URL passed as a query string parameter named 'continue'.  I wanted to emulate this API and process the 'continue' parameter in a wtform, but you cannot write something like:

```python
continue = wtforms.fields.StringField(widget=wtforms.widgets.HiddenInput())
```

And there is no way that I know of to have wtforms use 'continue' request parameter values when processing form data.  What I suggest is to add an optional kwarg and a read-only attribute on all Fields, so you could write:

```python
dest_url = wtforms.fields.StringField(
   widget=wtforms.widgets.HiddenInput(), param_name='continue')
```

Then the "name" of the field is 'dest_url', but to the HTML world the field uses 'continue'. The field above would process any query string or POST data that had 'continue' parameter data and generate this HTML:

```html
<input type="hidden" name="continue" value="http://path/to/next/url" />
```

**Comment by sirfz** [comment]
+1 for validating reCAPTCHA which is in a field called "g-recaptcha-response". It would be nice if we can override the field's name in its constructor without hacks.

**Comment by jmagnusson** [comment]
This is such an annoying limitation. I noticed when using `data` as an attribute name as well...

**Comment by azmeuk** [comment]
This issue looks like a duplicate for #205

**Comment by azmeuk** [comment]
With #601 it can be done with:

```python
_continue = wtforms.fields.StringField(name="continue", widget=wtforms.widgets.HiddenInput())
```
