### ISSUE TITLE
Email validator does not allow whitespace

### ISSUE THREAD

**Issue by MaicoTimmerman** [wtforms/wtforms#364]
"foo@bar.com " is a value that many mobile phone input into e-mail fields when enter login details. The validator will only allow "foo@bar.com", which causing login to fail.

**Comment by davidism** [comment]
And the updated one in master?

**Comment by MaicoTimmerman** [comment]
I'm running latest release 2.1 directly from pypi, have not checked the complete diff against master.

**Comment by kblomqvist** [comment]
Maybe filter first to remove whitespace.
