### ISSUE TITLE
Could not found tag: `0.6.4.dev0` WTForms (0.6.4.dev0)

### ISSUE THREAD

**Issue by geeksambhu** [wtforms/wtforms#365]
In my production machine, `WTForms` Version (`0.6.4.dev0`) is installed and could not find the tag `0.6.4.dev0` in this repository for pre-production environment setup. Since I have to maintain the exact replica of production server in pre-production setup this version `0.6.4.dev0` is my requirement. Help me with this :) 
Thanks

**Comment by davidism** [comment]
You appear to have installed a very old version and modified the version number. This is not a valid tag. We cannot support that.

**Comment by geeksambhu** [comment]
@davidism Is there any way to install the pip packages of this version from installed local files in `site-packages`.

**Comment by davidism** [comment]
0.6.4 is not a valid version, and if it was it would be *ancient*. I cannot offer support for it. You'll need to figure out why your project is configured in such a way. I would suggest upgrading instead.
