### ISSUE TITLE
MutlipleFileField

### ISSUE THREAD

**Issue by PatrickNa** [wtforms/wtforms#367]
Dear community,

I would like to use a multiple file field in my project. However, although it found such a field in this repository, I cannot import it. I receive an import error saying "cannot import name MultipleFileField".
This is the snippet, which causes the error:
```python
from wtforms.fields.simple import MultipleFileField
```

I have never opened an issue to an open source project like this. Please let me know if such a problem is not "worth" an issue.

Thank you guys!

**Comment by davidism** [comment]
You cannot import it because there has been no new release. There can be no new release until I have access to do so. You may use the code from #281 directly in the meantime, or install from source instead of PyPI.
