### ISSUE TITLE
FieldList Generating HTML Table Despite Specifying Widget

### ISSUE THREAD

**Issue by crhuber** [wtforms/wtforms#370]
I am trying to get my form to work with CSS framework called [Bulma][1]. 

I tried passing in *Widget=Input()*  but it still renders as a table. I also tried creating a macro but I still get a table

Everytime I try to render the location field. It renders as a table. I dont want it to be in a table. How can I control how it renders the HTML ?

**Macro**

        {% macro render_field(fieldlist) %}
        {% for field in fieldlist %}
        <div class="field">
          <label class="label">{{ field.name.label }}</label>
          <div class="control">
             {{ field(class="input", type="text", placeholder="Add location") }}
          </div>
        </div>
        {% endfor %}
    
       {% endmacro %}

**Form**

    class AddressEntryForm(Form):
        name = StringField('name', validators=[Required()])
    
    
    class AppointmentForm(Form):
        location = FieldList(FormField(AddressEntryForm), min_entries=2)

**HTML**

    {% extends "base.html" %}
    {% from "render_bulma.html" import render_field %}
    {% block title %} New Appointment {% endblock %}
    
    {% block page_content %}
      <section class="section">
        <div class="container">
          <h1 class="title">New Appointment</h1>
          <form method="POST" action="{{ url_for('main.appointment_create')}}">
            {{ form.csrf_token }}
           
           
            {{ render_field(form.location) }}
           
            <div class="field is-grouped">
              <div class="control">
                {{form.submit(class="button is-primary")}}
              </div>
            </div>
          </form>
        </div>
      </section>
    {% endblock %}

**Resulting HTML**

    <div class="field">
      <label class="label"></label>
      <div class="control">
         <table class="input" id="location-0" placeholder="Add location" type="text"><tr><th><label for="location-0-name">name</label></th><td><input id="location-0-name" name="location-0-name" type="text" value=""></td></tr></table><input id="location-0-csrf_token" name="location-0-csrf_token" type="hidden" value="..">
      </div>
    </div>

  [1]: https://bulma.io/documentation/form/general/

**Comment by ftm** [comment]
As given [here](https://github.com/wtforms/wtforms/blob/79840898a3e17b0ae535d9fdcff9537ef0e190b0/wtforms/fields/core.py#L813), `FormField` uses a `TableWidget` by default, however you should be able to specify one using the `widget` argument.

Try using [`ListWidget`](https://github.com/wtforms/wtforms/blob/79840898a3e17b0ae535d9fdcff9537ef0e190b0/wtforms/widgets/core.py#L63) and if that doesn't work you could always write your own widget to fit your exact needs.

In future, please direct usage related questions to another site such as StackOverflow. The issues board is meant to be used for bugs and other issues relating to the library itself.
