### ISSUE TITLE
IntegerField and other non StringField's raise "not callable" error.

### ISSUE THREAD

**Issue by jordaorodolfo** [wtforms/wtforms#372]
I'm struggling with a pesky issue that started to happen overnight in a small database-driven flask application with WTForms I'm doing. Sadly, th project is not on git where I could try to pinpoint if I ever did anything to make the error happen. Still, to the best of my knowledge, it just started all of a sudden without big contribution from my part in code.

Here goes... I have a Form which contains non StringField characters, to be specific:

    class ServiceModelForm(Form):
      startKM = IntegerField("KM Inicio", default=0)
      arriveKM = IntegerField("KM Chegada", default=0)
      endKM = IntegerField("KM Fim", default=0)
      #... among other fields here, there are quite a few ...

So, when I instance this beast in my simple route:

    @login_required
    def admin_service_view(service_id):
        if request.method == "GET":
            service = ServiceModel.get(id = service_id)
            serviceForm = ServiceModelForm().setChoicesFromDict(constants)
            return render_template("admin_service_view.html",
                                #...
                                form=serviceForm)

where this "choicesFromDict" simply sets the choiceFields choices in that form, it goes OK to the template, but as soon as jinja tries to call the field:

      File "/home/rjordao/Central/centralapp/templates/forms.html", line 14, in template
        {{tf(class="control input is-expanded")}}
    TypeError: 'IntegerField' object is not callable

And get this: it gets wierder. Initially I thought i screwed something up in the template and tried to simply call `form.startKM()` before rendering anything, right after serviceForm definition, and surprise! Same "not callable" error hapenning, while if I call `form.oneStringFieldProperty()`, it simply prints the html as it should. As a desperate measure, I opened a python(3) prompt and tried to instance a IntegerField Myself:

    Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
    [GCC 7.2.1 20171224] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from wtforms import *
    >>> class F1(Form):
    ...   a = IntegerField()
    ...   b = StringField()
    ... 
    >>> class F2(Form):
    ...   c = FormField(F1)
    ... 
    >>> f = F2()
    >>> f.c.a
    <wtforms.fields.core.IntegerField object at 0x7fea956547f0>
    >>> f.c.b
    <wtforms.fields.core.StringField object at 0x7fea95654940>
    >>> f.c.b()
    '<input id="c-b" name="c-b" type="text" value="">'
    >>> f.c.a()
    '<input id="c-a" name="c-a" type="text" value="">'

Therefore, the field works as normal outside of my App, but completely destroys itself otherwise. Anyone could share any ideas for this behavior? The worst part, as I briefly mentioned, is that the same code was working a few days ago (say, around 2018-01-28), then suddenly bonkers. For the record of any samaritan soul that is willing to help me, the version of the wtforms is the lastest you can get by pip'ng it, and the same goes for all the packages (flask, marshmallow, the usual stuff). Also, I'm not using ay of the flask-* integration packages.

Thanks a lot in advance!

**Comment by ftm** [comment]
Hello, are you still getting this error?

**Comment by jordaorodolfo** [comment]
Hello, @ftm ! Sorry, but I moved to another tech stack since I posted this issue, not because of this in particular: I promise! Thus, it has passed at least 2 months without touching the python source code. Is there anything else I could still help you with this?

**Comment by ftm** [comment]
Hi @jordaorodolfo, no worries! Your issue doesn't seem to have come up before not has it come up since so I'm not sure what was causing it.

If you still happen to have the code causing the issue lying around we'd be interested in seeing it just in case it comes up again.
