### ISSUE TITLE
Urgent: Please release 2.1.1 that fixes error with SQLAlchemy 1.2

### ISSUE THREAD

**Issue by ThiefMaster** [wtforms/wtforms#373]
https://github.com/wtforms/wtforms/blob/2.1/wtforms/ext/sqlalchemy/fields.py#L188-L190

In 1.2 `identity_key` returns a third item which is not really relevant here but breaks the list unpacking. I would suggest this change to support both 1.1 and 1.2:

```diff
-cls, key = identity_key(instance=obj)
+key = identity_key(instance=obj)[1]
```

For reference, here's the relevant part of the traceback with WTForms 2.1 and SQLAlchemy 1.2:

```
  File ".../wtforms/ext/sqlalchemy/fields.py", line 100, in _get_object_list
    self._object_list = list((text_type(get_pk(obj)), obj) for obj in query)
  File ".../wtforms/ext/sqlalchemy/fields.py", line 100, in <genexpr>
    self._object_list = list((text_type(get_pk(obj)), obj) for obj in query)
  File ".../wtforms/ext/sqlalchemy/fields.py", line 189, in get_pk_from_identity
    cls, key = identity_key(instance=obj)
ValueError: too many values to unpack
```

**Comment by ThiefMaster** [comment]
ah, actually it looks like it should be fixed in https://github.com/wtforms/wtforms-sqlalchemy as well

**Comment by davidism** [comment]
I can merge a patch for this, but I can't make new releases.

**Comment by jeancochrane** [comment]
Any plans for a patch @ThiefMaster @davidism? I'm running into this issue as well so I'd happy to submit one if it would help.

**Comment by ThiefMaster** [comment]
The problem is not the patch but getting a PyPI release. A possible fix is in my initial comment.

**Comment by jeancochrane** [comment]
I see now, thanks for the clarification! The monkeypatch snippet is very much appreciated.

**Comment by jeancochrane** [comment]
What's the procedure for releases @davidism? Is there a possibility of releasing a fix for this to the stable version before 3.0? The monkeypatch works fine, but it's not ideal.

**Comment by davidism** [comment]
There is no process, I have no access.

**Comment by jeancochrane** [comment]
Does that mean the PyPi package is unsupported?

**Comment by ThiefMaster** [comment]
It simply means that there is no way of updating it until @crast does a release or gives someone access to do releases...

**Comment by davidism** [comment]
Huh, I thought I posted a better explanation, it was on #374 instead:

@lepture and I are talking about something, but I have other projects to focus on in the immediate future. When we figure it out we'll announce it in an issue. We'll definitely be looking for other contributors.

It doesn't only matter that I get control of RTD and PyPI, I have no permissions for the org on GitHub, so have no control over all the infrastructure tied to that.

**Comment by jace** [comment]
Arrived here courtesy SQLAlchemy 1.2 breakage. Looks like only recourse at the moment is to downgrade to SQLAlchemy 1.1.17.

**Comment by ThiefMaster** [comment]
@jace: You can easily monkeypatch this: https://github.com/indico/indico/commit/c79c562866e5efdbeb5a3101cccc97df57906f76

So if you are already using SQLAlchemy 1.2 I would rather go for that instead of downgrading SQLAlchemy. If you are still on 1.1 though and don't need any of the features/fixes in 1.2 then you could  wait a bit, hoping there's a fixed WTForms release in the meantime.

**Comment by davidism** [comment]
I have access, I just need to get some free time now. There will be another release.

**Comment by galuszkak** [comment]
Hi @davidism when do You plan do that?

**Comment by davidism** [comment]
WTForms 2.2 has been released.
