### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by mblomdahl** [wtforms/wtforms#374]
It would be great being able to download a recent version from PyPI. 🥇

**Comment by davidism** [comment]
I do not currently have this ability. I am aware that people like libraries to release new versions when there are new features. If I am ever able to, I will make a new release.

**Comment by mblomdahl** [comment]
@davidism If @crast and @prencher are not available to grant you PyPI maintainer privileges, I'm thinking it might be an idea to open an "abandoned"-ticket with the Package Index? https://www.python.org/dev/peps/pep-0541/#continued-maintenance-of-an-abandoned-project

In the meanwhile, I uploaded my fork with a ...

    pip install twine && twine upload

It's located here: https://pypi.python.org/pypi/WTForms-fork-20180213/3.0.dev0

If you disagree with this, feel free removing it. And if I can help somehow, I'm happy to assist. I love this project! 💝

**Comment by davidism** [comment]
I can't remove forks, but please, please don't do that. People can already install from master through GitHub, and unless you're planning to keep that up to date and properly notify users, they will never get updates if any happen.

@lepture and I are talking about something, but I have other projects to focus on in the immediate future.

It doesn't matter if I get control of RTD and PyPI, I have no permissions for the org on GitHub, so have no control over most of the infrastructure being used.

**Comment by davidism** [comment]
I now have access.

**Comment by ChristophBerg** [comment]
Fwiw, wtforms just got removed from Debian testing (buster) because of this bug, along with everything that depends on it.
I uploaded a patched version now, but this should really be fixed upstream.
