### ISSUE TITLE
Can you make a release ?

### ISSUE THREAD

**Issue by sywesk** [wtforms/wtforms#378]
Hello dear maintainers,

We are currently running wtform on a production web site, and we discovered that the Email validator in the latest release is broken, but not on master. So we manually backported this change (from august 2016), but you know .. it feels ugly to do that and it's not a good practice.

Can you produce a new release, if possible ?
Thanks for doing your best maintaing this project !

@davidism I read on some other issue that you're going to do so when you have some time, but I wanted to show that we really need it.

**Comment by davidism** [comment]
Thank you, I'm already aware of this.
