### ISSUE TITLE
IPAddress validator return False for valid IPv6 address.

### ISSUE THREAD

**Issue by jirivrany** [wtforms/wtforms#385]
Hello,

the address "2001:718:1C01:1111::" is valid IPv6 address, however, the IPAddress validator returns False for it.

**Comment by vald-phoenix** [comment]
How about to use a default ipaddress module for validation purposes in this case? What do you think guys?

**Comment by davidism** [comment]
Yes, I'd like to do that. `ipaddress` is Python 3 only, although there is a [backport](https://pypi.org/project/ipaddress/) we could optionally require on Python 2.

**Comment by vald-phoenix** [comment]
So we can implement checks by means socket module that available on both versions of Python and reduce the length of the code significantly.

**Comment by jirivrany** [comment]
I'm using a custom validator based on the `ipaddress` module as a workaround. But as @davidism says, the Python 2 version would lead to external dependency. If it is not a problem, I can send my code as PR.

**Comment by davidism** [comment]
The dependency needs to be optional:

```python
try:
    import ipaddress
except ImportError:
    ipaddress = None

class SomeValidator:
    def __init__(self, ...):
        if ipaddress is None:
            raise Exception("Install 'ipaddress' for Python 2 support.")
        ...
```

PRs welcome.

**Comment by jirivrany** [comment]
Thanks @davidism then I will prepare one :) I have to rewrite the tests, to fit in the WTForms test suite, because I'm using slightly different environment for my tests.

**Comment by davidism** [comment]
We're using PyTest now, so feel free to ignore the existing unittest layout, I just haven't got around to rewriting them yet.

**Comment by jirivrany** [comment]
That's good, because I'm using pytest fixtures and mock. So I will use it in the PR and we can discuss necessary changes later.

**Comment by jirivrany** [comment]
The PR was created. Please let me know if anything needs to be changed.
