### ISSUE TITLE
Use Black to reformat code

### ISSUE THREAD

**Issue by davidism** [wtforms/wtforms#399]

**Comment by vald-phoenix** [comment]
You'd like to use some kind of a hook to reformat code according to Black before commit or management command?

**Comment by davidism** [comment]
I already did this in WTForms-Django, see [tox.ini](https://github.com/wtforms/wtforms-django/blob/d35ac883d0060cc3257fc74a3a8bc5363f86de0b/tox.ini#L29-L32) and [.pre-commit-config.yaml](https://github.com/wtforms/wtforms-django/blob/d35ac883d0060cc3257fc74a3a8bc5363f86de0b/.pre-commit-config.yaml). We can't do this here until there are no open pull requests, so that's step one.

**Comment by davidism** [comment]
@vald-phoenix if you want to do this again, it should be all right now.

**Comment by vald-phoenix** [comment]
Okay, I got it. I'll push PR today evening.
