### ISSUE TITLE
Allow non-boolean field flags

### ISSUE THREAD

**Issue by davidism** [wtforms/wtforms#406]
I want to support more HTML validation attributes, but currently the flags only set their value to `True`. For things like `maxlength`, we need to set the actual value.

My idea is to allow `field_flags` to be a function which returns a dict, deprecating and eventually removing the old tuple behavior.

**Comment by whb07** [comment]
This sounds great! A lot of the HTML5 standards can help reduce the minutiae of server side validations.

**Comment by Sohalt** [comment]
Any progress on this? Would you accept a pull request?

**Comment by davidism** [comment]
I'd be happy to review a pull request. Just take that as a given for any open issue that is not under discussion and doesn't have a PR already, no need to ask. :smile:

**Comment by Sohalt** [comment]
I've opened a pull request. The stylecheck is failing however, because some lines are too long. I'd like to have your opinion on that, since the contributing guidelines state, that there is no hard limit on line length.
