### ISSUE TITLE
Rewrite UnitTests to PyTest

### ISSUE THREAD

**Issue by jirivrany** [wtforms/wtforms#408]
@davidism mentioned [here](https://github.com/wtforms/wtforms/issues/385) that there is a plan to rewrite tests to be using PyTest layout instead of UnitTest. I have some spare time so I can start work on that if it helps to the project.

**Comment by davidism** [comment]
Yeah, if you want to start rewriting things to use pytest patterns, that's great. I think the PRs are low enough at this point to deal with the few tests they affect.

**Comment by davidism** [comment]
You can do it in phases, that's fine. Might be good to break large files apart into directories.

**Comment by jirivrany** [comment]
OK, then the first PR is out. I will think about the file split, that's a good idea.

**Comment by jirivrany** [comment]
@davidism I'm back from the vacations. I see that there are some changes in the directory structure. If I just run the tests by simple `py.test` I'm getting an import error. Can you please share how run the tests locally ? Then I can continue with the work on this issue ;-)

**Comment by davidism** [comment]
You must install the project in editable mode in your virtualenv: `pip install -e .`

**Comment by ftm** [comment]
Hi @jirivrany, I was wondering if this is still something you are working on?

**Comment by jirivrany** [comment]
Hi @ftm, to be honest, I'm currently overloaded by other tasks and I don't have time to work on this.  Should I close the issue? I hope that during the summer months I will have some time to return and finish this task.

**Comment by ftm** [comment]
Don't close the issue, since this is still something we'd like to do. Don't stress over it though, I'll make a branch and start converting the tests and if you want to contribute a few then you're welcome to :) .
