### ISSUE TITLE
Linter for repo

### ISSUE THREAD

**Issue by whb07** [wtforms/wtforms#416]
So as Black was introduced, I was thinking it might help to have a hook added as well to keep the syntax/style uniformly at pep8 guidelines.

I’ve worked with and seen other major repos use Flake8. Any thoughts?

Now that Black is added, are we using the standard 88 char line length?

**Comment by davidism** [comment]
Black uses flake8. Use its config example, add the pre-commit hook and add it to the tox stylecheck env too.
