### ISSUE TITLE
Consider to use pydocstyle alongside with Black

### ISSUE THREAD

**Issue by vald-phoenix** [wtforms/wtforms#419]
More details you can find here: [pydocstyle](https://github.com/PyCQA/pydocstyle)

**Comment by whb07** [comment]
Im down with this idea, but perhaps in the flake8 flavor (see #416 ) ? according to davidism the Black project already uses Flake8 which would be beneficial. I'll have to check it later.

**Comment by vald-phoenix** [comment]
Actually, Flake8 doesn't support checks of docstrings.

**Comment by vald-phoenix** [comment]
Black is good and you can use it as linter & fomatter, but it omits docstrings. You can use pydocstyle to lint errors and [pyment](https://github.com/dadadel/pyment) to format them according to [PEP 257](https://www.python.org/dev/peps/pep-0257/).

**Comment by davidism** [comment]
I'm not super concerned with docstrings other than wrapping them at 72, which I'm in the process of doing right now. We already build the docs and fail on error in CI, so that's probably good enough. Let's focus on code for a while. ;-)

**Comment by vald-phoenix** [comment]
Got it, thanks for response guys :+1:
