### ISSUE TITLE
move tests under src/

### ISSUE THREAD

**Issue by whb07** [wtforms/wtforms#425]
Seems that running the simple `pytest` command from the top level directory is broken post move to the src/ directory due to the imports being paths being changed. We can either move the tests/ directory under src/, or rename every import within the tests/ directory to account for the changes.

**Comment by davidism** [comment]
I missed a line in setup.cfg. Moving the tests wouldn't be correct.

**Comment by davidism** [comment]
You need to install the project in development mode.

```
pip install -e .
```
