### ISSUE TITLE
It's not possible to overwrite the Label text with an empty string

### ISSUE THREAD

**Issue by danieldiekmeier** [wtforms/wtforms#431]
Hey there! Long time WTForms user, first time ticketer.

I want to generate an empty label for a checkbox (so that I can create a custom styling), but I noticed that I can not overwrite the label text using

```
field.label("")
```

because of the `text = escape(text or self.text)` here: https://github.com/wtforms/wtforms/blob/master/src/wtforms/fields/core.py#L461

Of course, I can work around it by doing

```
field.label(" ")
```

which doesn't really make a difference to the generated HTML, so I'd be okay just doing that.

Is this on purpose, or would you accept a PR that checks if it's a string first?

**Comment by whb07** [comment]
Can you explain what you mean by this? If you're trying to render your own custom html label why do you want to use the form's?

**Comment by danieldiekmeier** [comment]
I thought that way I wouldn't have to reimplement what was essentially the exact same label that wtforms already provides, just with empty text. But I guess it doesn't really matter.

**Comment by davidism** [comment]
I see what you're trying to do, but I'd advise still rendering the label then hiding it with css, as that is much nicer for assistive technology like screen readers.

**Comment by danieldiekmeier** [comment]
@davidism Yes, sure! I was indeed rendering two labels: One as the actual label, and one as a custom checkbox, so I think it all worked out in the end.
