### ISSUE TITLE
'Not a valid choice' error when submitting option added to SelectField with Javascript

### ISSUE THREAD

**Issue by ghost** [wtforms/wtforms#434]
# Problem

If a form is submitted and the value of a `SelectField` is an option that was added by Javascript, WTForms will give a 'Not a valid choice' error message.

# Proposal

Add a keyword argument called `validate_choice` to `SelectField`'s `__init__` method that defaults to `True`. If it is `False`, WTForms will not check that the selected option is in the field's `choices` attribute.

**Comment by whb07** [comment]
Hi can you show some code or perhaps an example where you see this? What is the way you're validating once the POST request comes to the backend?

**Comment by hiphamster** [comment]
I just ran into exactly the same issue. 
in my form class i declare a SelectField like this:
`site = SelectField('site',  choices=[])`
later on, i set values via javascript using [selectize.js](https://github.com/selectize/selectize.js)
on submit i get 'Form validation failed', 'site: Not a valid choice'

**Comment by hiphamster** [comment]
I just found a [workaround](https://stackoverflow.com/questions/20856893/selectfield-in-wtforms-and-added-option-via-javascript/20862553#20862553). I followed the accepted answer, and created a new NonValidatingSelectField class:
```
class NonValidatingSelectField(SelectField):
    def pre_validate(self, form):
        pass 
```
But this is not obvious. It'd be nice to be able to pass a validation flag to the field, something like:
`site = SelectField('site', choices=[], validate=False)`

**Comment by ftm** [comment]
This seems like a reasonable feature to add, I'll write a PR up for it

**Comment by tvb** [comment]
@ftm I know this is an old thread, but I have the same issues with the `SelectMultipleField` and would like to set the `validate_choice` to `False` too. Any idea?

**Comment by ftm** [comment]
> @ftm I know this is an old thread, but I have the same issues with the `SelectMultipleField` and would like to set the `validate_choice` to `False` too. Any idea?

@tvb I did not add the `validate_choice` option to `SelectMultipleField` which was probably a mistake. If a PR is submitted to add the option then I'd be happy to accept it.

**Comment by lifeisawavesorideit** [comment]
In my opinion this is mandtory to be implemented.

**Comment by caffeinatedMike** [comment]
@hiphamster's seems to be the best option currently for `SelectMultipleField`s. I see the `validate_choice` option on the field, but it appears that it's completely overlooked during the validation process; as is evident when providing values via javascript and walking through the validation code upon calling `form.validate_on_submit()`. Was the feature started and just overlooked/never finished?

**Comment by AlverezYari** [comment]
Just ran into this one myself. Any new updates on that PR? Was it ever started?

**Comment by TomBubu** [comment]
+1 on the issue above. Please, any updates?

**Comment by kartikeyas00** [comment]
Any update on this PR yet??
