### ISSUE TITLE
Changing name causes data to silently not be returned 

### ISSUE THREAD

**Issue by thekevingibbons** [wtforms/wtforms#438]
In wtforms/src/wtforms/fields/core.py (as of writing, lines 333-337):
```
if formdata is not None:
    if self.name in formdata:
          self.raw_data = formdata.getlist(self.name)
    else:
          self.raw_data = []
```
If the code enters the else statement, it silently causes no data to return back from your form without giving an indication as to why. This can occur if you set the name attribute of a field after the instantiation of that field, for example, when one tries to create fields with dynamic names and values. 

Suggested fix: throw an error in the else statement that describes what causes your form not to return any data, something along the lines of "The name of this field changed between instantiation and the form being submitted; this is not allowed"

**Comment by davidism** [comment]
I don't think this behavior should change, at least not in the way described here. This seems like a specific case of #402.
