### ISSUE TITLE
SelectField injection protection

### ISSUE THREAD

**Issue by thekevingibbons** [wtforms/wtforms#439]
In SelectFields (and by extension, RadioFields, which is where I ran across this), a user accessing a form can change the value attributes of the fields using Chrome Dev Tools or any similar tool in another browser. When they submit the form, it accepts the modified values without complaint and passes them to the back end. 

Understanding that we should always protect against this sort of thing in our back-end verifications, it would increase security to guard against allowing this. For fields where the user is expected to choose from a pre-defined list of options, there could be a check that the value(s) submitted for a given field is from the set of values that was passed to the front end in the first place.

**Comment by davidism** [comment]
`SelectField` already checks the value during validation.
