### ISSUE TITLE
How to add a custom HTML <input> attribute ?

### ISSUE THREAD

**Issue by xiapoy** [wtforms/wtforms#440]
Hi,

I am starting with wtforms, it's very convenient 🙂

I would like to add the [`pattern` attribute](https://www.w3schools.com/TAGS/att_input_pattern.asp) to a `StringField`, to add [autofocus](https://www.w3schools.com/TAGS/att_input_autofocus.asp)... How can I do that?

Thanks!

**Comment by whb07** [comment]
Hi, so essentially something like this would work:

```python
 form.field(autofocus="")
```
that renders something like this:
```python
'<input autofocus="" type="text" value="">'
````

if you check the [HTML Standards](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofocusing-a-form-control:-the-autofocus-attribute) it states the attribute is a `boolean` type which is usually represented either by itself so just `autofocus` or setting it to the value of an empty string as seen above.

But more can be found in the [WTF-docs](http://wtforms.readthedocs.io/en/stable/fields.html) check it out! There are a couple times where there are "namespace" collisions like `class` but this is referenced in the docs.

**Comment by xiapoy** [comment]
Amazing. Thanks for your time! 🙂

**Comment by Glandos** [comment]
As a matter of fact, now you can also do it in the field declaration with `render_kw`:
```python
class AdminAuthenticationForm(FlaskForm):
    admin_password = PasswordField(_("Admin password"), validators=[DataRequired()], render_kw={"autofocus": True})
```
