### ISSUE TITLE
QuerySelectMultipleField breaks when query has no data and query_factory is None

### ISSUE THREAD

**Issue by mattkiz** [wtforms/wtforms#447]
Hi,

I was working with the QuerySelectMultipleField and noticed that when you set the query attribute to an empty list it will break. I think I tracked it down to a line in the wtforms.ext.sqlalchemy.fields module.
` def _get_object_list(self):
        if self._object_list is None:
            query = self.query or self.query_factory()
            get_pk = self.get_pk
            self._object_list = list((text_type(get_pk(obj)), obj) for obj in query)
        return self._object_list`
I think it could be fixed by self.query or ... to  self.query is not None or ... because it would be more explicit.

**Comment by davidism** [comment]
`wtforms.ext` has been moved to separate repositories. Please report this against [wtforms-sqlalchemy](https://github.com/wtforms/wtforms-sqlalchemy).
