### ISSUE TITLE
html_params and class and class_

### ISSUE THREAD

**Issue by xyzones** [wtforms/wtforms#449]
Hello,

I have a form created with model_form of flask_mongoengine.wtf

```python
    field_args = {
      'bio': {'render_kw':{'class_':"summernote"}},
    }
    exclude = ['created_at','created_by']
    form = model_form(Author,exclude=exclude,field_args=field_args)
```

I have a HTML 
```jinja
 {{ field(class='form-control', **kwargs) }}
```

for which the TextArea widget correctly outputs 
```jinja
<textarea class="form-control" class="summernote" id="bio" name="bio">text</textarea>
```

However all browsers are removing the extra class tag. It would be good to rewrite the html_params so that multiple class tags are combined into one. 

**expected output:**
```jinja
<textarea class="form-control summernote" id="bio" name="bio">text</textarea>
```

I am using 

Package | Version
--------  | --------
Flask | 1.0.2
Flask-WTF |   0.14.2
flask-mongoengine | 0.9.5
WTForms |  2.2.1

Thanks,

**Comment by davidism** [comment]
For flexibility, we'd have to allow names further down the line override the value, rather than combining, so that you can replace values rather than just append.

**Comment by azmeuk** [comment]
I could reproduce with:

```python
>>> import wtforms                                                                                                  

>>> class F(wtforms.Form): 
...     foo = wtforms.StringField(render_kw={'class_':'summernote'})                                                

>>> F().foo(**{"class": "form-control"})                                                                             
Markup('<input class="form-control" class="summernote" id="foo" name="foo" type="text" value="">')
```

@davidism are you saying that `form-control` should override `summernote`?

**Comment by davidism** [comment]
I think that's what I meant, yes. Do any normalization then overwrite existing keys.
