### ISSUE TITLE
wtforms 2.2.1 setup.py test Python 3 Syntax Error

### ISSUE THREAD

**Issue by skullgoblet1089** [wtforms/wtforms#459]
Background:
- I am trying to make a local build of WTForms-2.2.1 using a Python 3.6.2 venv.
- I was able to use the following command to build the project locally:
```bash
python setup.py build |& tee setup.py_build.out
```
- However the following command resulted in a syntax error:
```bash
python setup.py test |& tee setup.py_test.out
...
File "/u1/glafata/Downloads/WTForms-2.2.1/tests/ext_appengine/test_ndb.py", line 59
    print list(form.author.iter_choices())
SyntaxError: invalid syntax
```
.out files:
[setup.py_build.out.txt](https://github.com/wtforms/wtforms/files/2724410/setup.py_build.out.txt)
[setup.py_test.out.txt](https://github.com/wtforms/wtforms/files/2724411/setup.py_test.out.txt)

Questions:
- Can I assume local build is OK despite Syntax Error in /tests/ext_appengine/test_ndb.py line 59?
- If not, should I use Python 2.7 to perform setup.py operations instead of Python 3? I assume the resulting build would then be compatible with Python 3.6?

**Comment by davidism** [comment]
I'm not really sure why you're using the commands you're using. To build a dist locally, use `setup.py sdist` or `setup.py bdist_wheel`, not `build`. `build` has nothing to do with `test`. The `setup.py test` command also isn't supported, you should use `tox` to run the tests: `tox -e py`. `ext` has been deprecated, so those tests shouldn't run anyway. Regardless, development focus is on master, which moved the tests to use pytest.
