### ISSUE TITLE
Integer field - default value

### ISSUE THREAD

**Issue by karliner1729** [wtforms/wtforms#461]
Hey guys,
first let me appreciate your work, it's amazing!
I'm trying to create flask-based easy calculator of net income where user provides some informations and then net income is computed. The problem is when one of the unnecessary IntegerFields is empty, I of course get '* TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'*' error.

I managed to change the value with this piece of code
`
if form.IntegerField.data == None:
    form.IntegerField.data == 0
else:
    pass
`

But this seems like really not efficient way of doing this since I have many variables. I also tried
`class Form(FlaskForm):
    field = IntegerField('Please enter your gross income', default=0)`

But when the user accidentally delete the default value, the page returns TypeError. I googled a lot but no solution seems to work for me.

I asked the same question on reddit (https://www.reddit.com/r/learnpython/comments/aj65pj/wtforms_if_value_is_not_provided_integerfield/)

But none of the replies worked for me.

I tried 

`IntegerField = IntegerField('Enter your gross income', filters=[lambda x: 0 if x is None else x]`

but that ain't work either.
I really appreciate your work. Thank you in advance.

**Comment by ftm** [comment]
Hi @karliner1729, I can't seem to reproduce your error. If you are still having this issue could you post a minimal working example so we can try to reproduce it as well as include the actual error message you receive.

**Comment by ftm** [comment]
It's been nearly three months since I asked for an example and none has been given so I'm going to assume this is no longer an issue.
