### ISSUE TITLE
wtforms.validators.HostnameValidation does not allow underscores in the domain portion of the URL

### ISSUE THREAD

**Issue by camillser** [wtforms/wtforms#462]
Hey, there seems to be a problem with the way the wtforms.validators.HostnameValidation is handling the underscore character. Underscores should be allowed in domain names per [1]. This problem was found using wtforms.validators.URL and that validator depends on wtforms.validators.HostnameValidation.

Reproducible example:
```
import wtforms.validators
validator = wtforms.validators.HostnameValidation()
validator("a_b.example.org")
```

The result of the above code is that validator returns False. The expected result is True.

[1] https://tools.ietf.org/html/rfc2181#section-11

**Comment by ftm** [comment]
Closing issue as it has been fixed by the PR referenced above
