### ISSUE TITLE
Segmentation fault when SelectField choices is a list.

### ISSUE THREAD

**Issue by backwardspy** [wtforms/wtforms#464]
Project dependencies:

```
$ cat Pipfile
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
flask = "*"
jinja2 = "*"
wtforms = "*"
flask-wtf = "*"
requests = "*"

[requires]
python_version = "3.6"
```

The SelectField in question:

```python
option = SelectField(label='Option', choices=["a", "b", "c"])
```

Running the server then hitting the page in my browser:

```
$ flask run
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
'flask run' terminated by signal SIGSEGV (Address boundary error)
```

Changing the choices to the correct format (list of tuples) fixes the error.
I ran through the code in GDB but it's not clear where exactly the segfault occurs. It seems to appear somewhere amongst Jinja2 and/or WTForms.

Is this directly related to WTForms, or should I open this issue on Flask-WTF/Jinja2 instead?
If the former, is it worth placing a type check on this field to prevent the list getting through to the templating engine?

**Comment by ftm** [comment]
I can't seem to reproduce this exact error when using just WTForms, which makes me think that it might be coming from a different dependency. However as you can see from the message generated and from the [docs](https://wtforms.readthedocs.io/en/stable/fields.html#wtforms.fields.SelectField), this is not how this field is meant to be used.

```python
>>> from wtforms import Form, SelectField
>>> class OptionForm(Form):
...     options = SelectField(label="Option", choices=["a", "b", "c"])
... 
>>> form = OptionForm(options="a")
>>> form.options.data
'a'
>>> form.validate()
False
>>> form.errors
{'options': ['not enough values to unpack (expected 2, got 1)']}

```

**Comment by backwardspy** [comment]
Fair enough. I expect you're right; it's probably some obscure intersection of the dependencies in this project. Thank you for taking the time to investigate this.

**Comment by shiki009** [comment]
We are also seeing this with an input where choices is a list of lists(3):

`[['ashkj', 'sadfsdf', 'asdfsad'], ['adsfasfd', 'asdfsdf', 'asdfasd']]`
