### ISSUE TITLE
passing value null will cause TypeError

### ISSUE THREAD

**Issue by xiluoduyu** [wtforms/wtforms#466]
https://github.com/wtforms/wtforms/blob/283b2803206825158834f1828bbf749c129b7c47/src/wtforms/fields/core.py#L673

when i pass a null value, here will cause type error which won't be caught: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'. 
![image](https://user-images.githubusercontent.com/5248983/52552106-0639f600-2e1a-11e9-89df-8eb37910f33f.png)

**Comment by ftm** [comment]
Could you post some example code which generates this error?

**Comment by xiluoduyu** [comment]
> Could you post some example code which generates this error?

form field definition:
ad_type = IntegerField('ad_type', validators=[Optional(), AnyOf(avail_adtypes)])

post json body:
{
    "ad_type": null
}

**Comment by davidism** [comment]
WTForms is not meant for validating JSON. This may change in a future release, see #198.
