### ISSUE TITLE
Adding a class to labels via Python

### ISSUE THREAD

**Issue by anfractuosity** [wtforms/wtforms#468]
Hi,

Unless I'm mistaken there doesn't seem to be a way to change the class of a label via Python
programmatically.

I'm looking at:
https://github.com/wtforms/wtforms/blob/master/src/wtforms/fields/core.py#L436

It looks like kwargs is only passed to __call__ and doesn't seem to have a render_kw field like Field objects.

The reason I'm looking for this, is so that if i call form.validate() I can programmatically add a class to labels for invalid fields, to colour them red for instance.

Cheers

**Comment by ftm** [comment]
You can modify the HTML class of the label by passing in a `class_` argument when rendering the label in your template, for example:

```jinja2
{% if form.name.errors %}
    {% set label_class='form-label invalid' %}
{% else %}
    {% set label_class='form-label' %}
{% endif %}

{{ form.name.label(class_=label_class) }}
```

In future, please post usage related questions to a site such as StackOverflow - this issues board should be for issues relating to the library itself, not its usage, and include a minimal, complete, and verifiable example.
