### ISSUE TITLE
Override field's name attribute in FormField?

### ISSUE THREAD

**Issue by qiangzhichen** [wtforms/wtforms#469]
if I hava a post data with 
`my_data = ImmutableMultiDict([('myTitle', ('scheduledStartTime', 1549974840000))])`
I want to create a form to validator it , I use FormField to create Form
```
class TitleForm(wtforms.Form):
    scheduledStartTime = MyTimeField()


class PostForm(wtforms.Form):
    myTitle = FormField(TitleForm)


my_form = PostForm(my_data)
print(my_form.data)
```
However it doesn't works, and I want to change myTitle to my_title,scheduledStartTime to shceduled_start_time, so ,how can i do it

**Comment by ftm** [comment]
This issues board is for issues relating to WTForms itself, not for usage related questions. Please post usage related questions on a website such as StackOverflow, making sure to include a Minimal, Complete, and Verifiable example
