### ISSUE TITLE
Error: No module named 'wtforms.csrf'

### ISSUE THREAD

**Issue by claudefalbriard** [wtforms/wtforms#478]
After an upgrade of flask-wtf (#Successfully installed Flask-WTF-0.14.2)
I get the following error:  

from wtforms.csrf.core import CSRF
ModuleNotFoundError: No module named 'wtforms.csrf'

Please advice.

**Comment by davidism** [comment]
Ensure you're using the latest version of WTForms. Also ensure you haven't called a package at the top level of your project "wtforms".
