### ISSUE TITLE
options for Regexp to validate raw data

### ISSUE THREAD

**Issue by kaiwensun** [wtforms/wtforms#487]
Regex now can only validate text-based fields. If the field is of non-string type, eg. FloatField or IntegerField, we may still want to use Regex to validate the input. One potential use case is to validate a price in FloatField type to match ^\d*(\.\d{1,2})?$

Here is a PR: https://github.com/wtforms/wtforms/pull/465

**Comment by ftm** [comment]
Please don't clutter the issues board creating posts to try and bring attention to PRs you've already made.
