### ISSUE TITLE
Optional DateField throwing "Not a valid date value" error for empty input

### ISSUE THREAD

**Issue by openbrian** [wtforms/wtforms#489]
This is similar to #60, but let's not use DataRequired().

```python
from flask import Flask, render_template
from flask_wtf import FlaskForm
from flask_wtf.csrf import CSRFProtect
from wtforms import DateField

class MyForm(FlaskForm):
  event = DateField()


app = Flask(__name__)
app.config['SECRET_KEY'] = 'sdlfkjsfsdfsdfsdfkjsdlf'
csrf = CSRFProtect()
csrf.init_app(app)


@app.route("/", methods=('GET', 'POST'))
def hello():
  form = MyForm()
  if form.validate_on_submit():
    return "success"
  return render_template('index.html', form=form)
```

Simple template.

```jinja
<form method="POST" action="/">
  {{ form.csrf_token }}
  {{ form.event.label }}
  {{ form.event }}
  <input type="submit" value="Go">
</form>
```

Submitting with 1934-11-9 results in "success".  Submitting an empty form, results in "Not a valid date value."

I think the bug is here in DataField.process_formdata() where we have "if valuelist".  valuelist here is a list with 1 item, the empty string [''].  That's truthy and parsing will continue.

In all other non-time fields we use valuelist[0].  Shouldn't we do that here so we don't parse empty data?

LMK if you want a PR.

**Comment by openbrian** [comment]
Well I suppose I assumed that if it's not DataRequired() that it was by default Optional().  Still seems kind of silly to parse empty input during processing.

**Comment by azmeuk** [comment]
I am trying to reproduce the behavior you are describing:

```python
>>> import wtforms
>>> from tests.common import DummyPostData
>>> class MyForm(wtforms.Form): 
...     event = wtforms.DateField()
>>> MyForm(DummyPostData({"event": "1934-11-9"})).validate() # [1]
True
>>> MyForm(DummyPostData({"event": ""})).validate()          # [2]
False
```
Basically, are you saying that `[1]` is an expected behavior but `[2]` is not?

**Comment by augnustin** [comment]
:+1: here. Why did the issue get closed?

@azmeuk yes `MyForm(DummyPostData({"event": ""})).validate()` should be `True` if `event` is not required.

@openbrian did you find your way out?

**Comment by pytrumpeter** [comment]
Can we reopen this?  Still running into this and there isn't an easy workaround that I can find.

**Comment by azmeuk** [comment]
> @azmeuk yes `MyForm(DummyPostData({"event": ""})).validate()` should be `True` if `event` is not required.

Can you explain why you think this should be `True`?
This is not clear to me what the empty values should be. Currently we have this behavior:

```python
>>> class MyForm(wtforms.Form): 
...     event = wtforms.DateField()
>>> MyForm(DummyPostData({"event": "1934-11-9"})).validate()
True
>>> MyForm(DummyPostData({"event": ""})).validate()
False
>>> MyForm(DummyPostData()).validate()
True

>>> class MyForm(wtforms.Form): 
...     event = wtforms.DateField(validators=[wtforms.validators.Optional()])
>>> MyForm(DummyPostData({"event": "1934-11-9"})).validate()
True
>>> MyForm(DummyPostData({"event": ""})).validate()
True
>>> MyForm(DummyPostData()).validate()
True


>>> class MyForm(wtforms.Form): 
...     event = wtforms.DateField(validators=[wtforms.validators.DataRequired()])
>>> MyForm(DummyPostData({"event": "1934-11-9"})).validate()
True
>>> MyForm(DummyPostData({"event": ""})).validate()
False
>>> MyForm(DummyPostData()).validate()
False
```

So, with `Optional` the value being empty or absent is valid, with `DataRequired` the value being empty or absent is invalid, and by default the value can be absent but cannot be empty.
I think the question is larger than just `DateField` as `IntegerField` behaves exactly the same ways. I think this is related to the default value discussion on #402
