### ISSUE TITLE
Document for HostnameValidation

### ISSUE THREAD

**Issue by BlackMetalz** [wtforms/wtforms#501]
Hi, I see in the source code have method HostnameValidation for validating but no document for this in website https://wtforms.readthedocs.io/en/stable/validators.html. 

It isn't ready to use or I have missed something :)

https://github.com/wtforms/wtforms/blob/master/src/wtforms/validators.py#L605

**Comment by ftm** [comment]
Hello, the `HostnameValidation` class is only meant for internal use, and is therefore not included in the documentation. As discussed in #474 and #463, this class may soon disappear so we recommend that you do not rely on it.

**Comment by BlackMetalz** [comment]
Please dont remove that because it was a great validator to valid host and ip address
