### ISSUE TITLE
Provide a way to set a widget inner HTML

### ISSUE THREAD

**Issue by azmeuk** [wtforms/wtforms#504]
At the moment I cannot find an easy way to set a `TextAreaField` in a Jinja context just by passing arguments to the field `__call__` function.

```python
>>> import wtforms
>>> class MyForm(wtforms.Form):
...     ta = wtforms.fields.TextAreaField()
>>> MyForm().ta(value="foobar")
'<textarea id="ta" name="ta" value="foobar"></textarea>'
```

This syntax would have been OK for a classical text input, but to be displayed properly I need to be able to produce `'<textarea id="ta" name="ta">foobar</textarea>'`.

What about treating a special `content_` parameter as an addition to the inner HTML? So we could be able to write something like:
```python
>>> MyForm.ta(content_="foobar")
'<textarea id="ta" name="ta">foobar</textarea>'
```
It seems [I am not the only one](https://stackoverflow.com/questions/5117479/wtforms-how-to-prepopulate-a-textarea-field) interested by such a feature.

If it is OK for you, I am volunteer to write a pull request for this.

What do you think?

**Comment by davidism** [comment]
`MyForm(data={"ta": "default"})`, or `form.ta(placeholder="hint")`

**Comment by azmeuk** [comment]
Thank you for your answer.
Maybe I should have been more precise: in a Jinja context, forms are generally already initialized by some python code. So `MyForm(data={"ta": "default"}).ta(),` would not be ok here as the form constructor would have already been called.

And `form.ta(placeholder="hint")` just set the textarea placeholder, and not its actual value.

What do you think?

**Comment by davidism** [comment]
Do complex processing, such as initializing with defaults, in Python before passing to the render template context.
