### ISSUE TITLE
FieldList default data with missing request entries

### ISSUE THREAD

**Issue by azmeuk** [wtforms/wtforms#509]
There is a strange behavior with wtforms 2.2

If you initialize a form with some request data and an object, and you forget a field in the request data, then the form will take the object's value.

```python
>>> import wtforms
>>> from tests.common import DummyPostData
>>> class Form(wtforms.Form):
...     foo = wtforms.StringField()
... 
>>> class Obj:
...     foo = "OK"
... 
>>> Form(DummyPostData({}), Obj()).data
{'foo': 'OK'}
```

Now if you do the same experiment with a `FieldList`, the form will not take the object values.
```python
>>> class Form(wtforms.Form):
...     bars = wtforms.FieldList(wtforms.StringField(), min_entries=3)
... 
>>> class Obj:
...     bars = ["one", "two", "three"]
... 
>>> Form(DummyPostData({'bars-0': 'A'}), Obj()).data
{'bars': ['A', '', '']}
```

Here I would have expected `{'bars': ['A', 'two', 'three']}`.

What do you think? If this is indeed an unwanted behavior, I volunteer to provide a pull request.

**Comment by davidism** [comment]
Closing, see discussions on linked closed PRs.
