### ISSUE TITLE
HostnameValidation (and thus Email validation) doesn't allow for double hyphens

### ISSUE THREAD

**Issue by divad** [wtforms/wtforms#512]
The following is a valid domain name:

`g--gle.com` 

however wtforms doesn't think so:

```
>>> from wtforms.validators import HostnameValidation
>>> validate = HostnameValidation()
>>> validate('google.com')
True
>>> validate('g--gle.com')
False
```

Here is an example of this domain name in use: https://www.f--kthegame.com

```
>>> validate('f--kthegame.com')
False
```

This affects all the validators using Hostname Validation, such as the e-mail validator.

More info here: https://stackoverflow.com/questions/16468309/can-domain-name-have-two-continuous-hyphens

**Comment by azmeuk** [comment]
This have been fixed by #540.
