### ISSUE TITLE
DateTimeField can't be empty string

### ISSUE THREAD

**Issue by lwh31415** [wtforms/wtforms#517]
I know a little english,sorry. 
When we design a form, we want a field to be a empty string. But a DateTimeField cannot be a empty string. 
DateTimeField(wtforms/src/wtforms/fields/core.py)‘s process_formdata code show as below：
```python
def process_formdata(self, valuelist):
        if valuelist:
            date_str = " ".join(valuelist)
            try:
                self.data = datetime.datetime.strptime(date_str, self.format)
            except ValueError:
                self.data = None
                raise ValueError(self.gettext("Not a valid datetime value"))
```

**Comment by aklaver** [comment]
Using wtforms.ext.dateutil  I found I could override this by doing:

task_end = DateTimeField("End", [validators.Optional(strip_whitespace=True)],
                             display_format='%m/%d/%Y %H:%M:%S',
                             )

**Comment by ddmee** [comment]
Why was this issue closed? It also applies to the DateField

```python
class DateField(DateTimeField):
...
    def process_formdata(self, valuelist):
        if not valuelist:
            return

        date_str = " ".join(valuelist)
        try:
            self.data = datetime.datetime.strptime(date_str, self.format).date()
        except ValueError:
            self.data = None
            raise ValueError(self.gettext("Not a valid date value."))
```

It seems like you cannot have an empty date field? I want a datefield to be optional.

```python
DateField('Optional Date')
```

Surely it should be optional until add the data required validator like so:

```python
DateField('Not Optional Date', validators=[DataRequired()])
```
