### ISSUE TITLE
`description` property isn't rendered for `BooleanField`

### ISSUE THREAD

**Issue by shnela** [wtforms/wtforms#518]
I have following form definition:
```
class Form(FlaskForm):
    text = StringField(description='Some visible text')
    unique = BooleanField(description="Won't be rendered")
```

And below I'm presenting how does html rendered by following template loooks like:
```
{% for field in form %}
    {{ wtf.form_field(field) }}
{% endfor %}
```
```
<div class="form-group "><label class="form-control-label" for="text">Text</label>
        <input class="form-control" id="text" name="text" type="text" value="">
        <small class="form-text text-muted">Some visible text</small>
</div>
<div class="form-check">
      <label class="form-check-label">
      <input class="form-check-input" id="unique" name="unique" type="checkbox" value="y">
Unique
     </label>
</div>
```

Here's how it looks like live:
![image](https://user-images.githubusercontent.com/3773836/67092786-702c4b80-f1b0-11e9-860e-b29965f40fe6.png)

**Why isn't `description` for `BooleanField` rendered?**

**Comment by davidism** [comment]
You'll need to consult Flask-Bootstrap, or whatever extension is providing the `wtf` template macros, about that. WTForms doesn't provide this.

**Comment by shnela** [comment]
right...
