### ISSUE TITLE
When will the SelectField validate_choice feature be available?

### ISSUE THREAD

**Issue by front5stoneybaloney** [wtforms/wtforms#539]
I can see the PR for fixing the validation error that occurs when you are using javascript to dynamically add choices for the `SelectField`. When will I be able to use the `validate_choice=Trues/False` thingy? It will be so useful now that things like jquery-Select2 are growing more and more popular. 
The 'newest' version of WTForms (2.2.1) is from June 2018 which is weird given that you appear to be actively supporting and developing it. Is there a planned date for a new release at all?

**Comment by PanderMusubi** [comment]
Looking forward to a new release too please.

**Comment by davidism** [comment]
I'm sorry, we do plan to make a release but we can't commit to a timeline. It will be released when maintainers have time to make a release. I do not currently have time, other maintainers have been added to the project but they have their own schedules as well.

**Comment by PanderMusubi** [comment]
Thanks for the information.
