### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by NathanUrwin** [wtforms/wtforms#543]
Hey @crast @prencher @davidism :wave:

Just want to say you all have done a great job with this project! With that being said, it's been almost 2 years since a release. Would one of the maintainers be able to create a new release?

Thanks for your time and all your hard work! :smile:

**Comment by davidism** [comment]
Thanks for your interest! FYI, crast and prencher have not been maintainers for quite some time. @ftm is the other active maintainer, and unfortunately neither of us have had much time to devote to this recently.

Between all the other projects I maintain, I probably won't be able to do more than help others who are interested in maintaining for now. If you'd be interested, I can add you to the group.

Closing this as I don't usually leave these types of issues open. I'm open to making another release, but I'm not confident in the state of the repository right now to know if it's ready for a release (bugs closed, changelog up to date, all tests passing, etc.)
