### ISSUE TITLE
[feature request/question] Form wise errors

### ISSUE THREAD

**Issue by alexef** [wtforms/wtforms#55]
On form validation I want to raise errors such as: "at least a field must be filled" which do not belong to one field, but to the form as a whole.

Would it be possible to raise have them on the form? (I'm currently using a hidden field and validating these kind of errors on it).

**Comment by jmagnusson** [comment]
Is any work being done for this? A perfect use-case for this is in a login-form where you want to tell the user that the combination of the username and password field is invalid.

**Comment by kissgyorgy** [comment]
I think this is actually not needed, because you can always override the `validate` method and check for field errors after calling the superclass `validate` method there.
For a complex example, see: http://flask.pocoo.org/snippets/64/

**Comment by davidism** [comment]
Warehouse (PyPI) has this: https://github.com/pypa/warehouse/blob/efc2a3fc18783d4375f878de548318d00f206924/warehouse/forms.py#L109-L116

They use the string `"__all__"` for the key, @azmeuk suggested `None`. Pinging @di because he edited the code I linked.
