### ISSUE TITLE
End python2 support

### ISSUE THREAD

**Issue by azmeuk** [wtforms/wtforms#552]
I open this ticket to discuss the end of the python2 support. The pallet community [seems to want to end](https://palletsprojects.com/blog/ending-python2-support/) the support, but how is it doable now in wtforms? I suppose that would require a major version bump.

Could wtforms 3 be the version that would drop python 2 support?

**Comment by davidism** [comment]
Absolutely drop Python < 3.6 support and bump the version to 3. I've done it to all the projects except Click now, you can find the "Drop Python 2" PRs and check the commits for the kinds of things I looked for. The pyupgrade pre-commit hook is really helpful.
