### ISSUE TITLE
2.3.0 breaks rendering of SelectField with no choices

### ISSUE THREAD

**Issue by c-thiel** [wtforms/wtforms#585]
### Actual Behavior

```python
from wtforms import Form, SelectField, validators

class MyForm(Form):
    my_field = SelectField(label='MyField', choices=[])

form = MyForm()
form.meta.render_field(form.my_field, {})
```

Results in
```python
IndexError: list index out of range
```

Due to:
https://github.com/wtforms/wtforms/blob/0a63864317ce3260d14a11260ed16e2f02037f56/src/wtforms/fields/core.py#L512

### Environment

* Python version: Any
* wtforms version: 2.3.0

**Comment by azmeuk** [comment]
Should be fixed by #582
