### ISSUE TITLE
documentation search is broken

### ISSUE THREAD

**Issue by cmdlinebeep** [wtforms/wtforms#599]
I couldn't find any other way to get this feedback to the webhost (no contact form, email address that I saw).

Anyway, go to the documentation site:
https://wtforms.readthedocs.io/en/2.3.x/ 
and in the quick search, try anything (I did "subfield" but it seems to be broken on all my searches)
and then click on any of the search results and they will take you to a Page Not Found error.

**Comment by davidism** [comment]
I can't say when this will be fixed. The configuration is the same as all my other projects, yet this is the only one that is failing (in this way, Click also fails in a similar but different way). I pinged a RTD dev to see if they can spot anything.

**Comment by davidism** [comment]
cc @davidfischer

**Comment by davidism** [comment]
This is fixed now.
