### ISSUE TITLE
QuerySelectField does not seem to work with the data= argument of the WTForm

### ISSUE THREAD

**Issue by davidmoseler** [wtforms/wtforms#600]
When instanciating a WTForm with the request.form object directly, the id values of QuerySelectFields are converted into the corresponding instances of the corresponding models. But the same does not happen when using the "data" attribute of the WTForm instead. This is important for handling json request data.

Maybe I'm just using the data= parameter wrong, idk. A workaround is to import MultiDict from Werkzeug, wrap the json and then pass it to the WTForm constructor.

### Actual Behavior

```python
form = WTForm(data = request.json)
print(form.sqlalchemy_model_field.data)

#string value of the id of the sqlalchemy model instance
```

### Expected Behavior

```python
form = WTForm(data = request.json)
print(form.sqlalchemy_model_field.data)

#sqlalchemy model instance
```

**Comment by davidism** [comment]
Data should be processed Python data, not incoming form data.
