### ISSUE TITLE
SelectMultipleField default values are ignored when a request object exists

### ISSUE THREAD

**Issue by azmeuk** [wtforms/wtforms#604]
When a request object and a data dict are passed to a form, the data dict values for `SelectMultipleField` are ignored.

```python
>>> import wtforms, werkzeug
>>> choices=[("foo", "foo"), ("bar", "bar"), ("baz", "baz")]
>>> requestform = werkzeug.datastructures.ImmutableMultiDict([])

>>> class F(wtforms.Form):
...     multiple = wtforms.SelectMultipleField(choices=choices)

>>> F(multiple=["foo", "bar"]).multiple()
Markup('<select id="multiple" multiple name="multiple"><option selected value="foo">foo</option><option selected value="bar">bar</option><option value="baz">baz</option></select>')

>>> F(requestform, multiple=["foo", "bar"]).multiple()
Markup('<select id="multiple" multiple name="multiple"><option value="foo">foo</option><option value="bar">bar</option><option value="baz">baz</option></select>')
>>> # Nothing is 'selected' here...
```

A simple workaround is `F(requestform or None, multiple=["foo", "bar"]).multiple()` but I think this should probably work without it.

The problem does not exist with `SelectField`:

```python
>>> class G(wtforms.Form):
...     single = wtforms.SelectField(choices=choices)
>>> G(requestform, single="foo").single()
Markup('<select id="single" name="single"><option selected value="foo">foo</option><option value="bar">bar</option><option value="baz">baz</option></select>')
```

### Environment

* Python version: 3.8
* wtforms version: 2.3.1 and master

**Comment by davidism** [comment]
I think this is a bug with `SelectField`, not `SelectMultipleField`. If form data was passed in, default data should be ignored. But with many web frameworks it's impossible to tell that a form wasn't submitted vs submitted but empty by only looking at the form data object. This is a specific case of #402.
