### ISSUE TITLE
The format of the error messages are not unified (ending period)

### ISSUE THREAD

**Issue by greyli** [wtforms/wtforms#613]
In general, some error messages end with a period:

```mo
#: src/wtforms/validators.py:269 src/wtforms/validators.py:294
msgid "This field is required."
msgstr ""

#: src/wtforms/validators.py:327
msgid "Invalid input."
msgstr ""

#: src/wtforms/validators.py:387
msgid "Invalid email address."
msgstr ""

#: src/wtforms/validators.py:423
msgid "Invalid IP address."
msgstr ""

#: src/wtforms/validators.py:466
msgid "Invalid Mac address."
msgstr ""
```

but some don't:
```mo
#: src/wtforms/csrf/core.py:96
msgid "Invalid CSRF Token"
msgstr ""

#: src/wtforms/csrf/session.py:63
msgid "CSRF token missing"
msgstr ""

#: src/wtforms/csrf/session.py:71
msgid "CSRF failed"
msgstr ""

#: src/wtforms/csrf/session.py:76
msgid "CSRF token expired"
msgstr ""

#: src/wtforms/fields/core.py:534
msgid "Invalid Choice: could not coerce"
msgstr ""

#: src/wtforms/fields/core.py:538
msgid "Choices cannot be None"
msgstr ""

#: src/wtforms/fields/core.py:545
msgid "Not a valid choice"
msgstr ""
```
source: https://github.com/wtforms/wtforms/blob/master/src/wtforms/locale/wtforms.pot

This make the UI look a little inconsistent when these messages show together.

![image](https://user-images.githubusercontent.com/12967000/83321987-bab59080-a286-11ea-93f0-470cea4d1208.png)

Do we need to add periods for these messages? If yes, I can submit a PR to fix this. This PR may involve these changes:

- Update the messages in the source
- Regenerate the pot file
- Update the messages in the test
- Maybe also update all the translations (some translation adds the missing period for the target language, some don't)?

**Comment by azmeuk** [comment]
Thank you for your reporting.
I suppose it would make sense to have periods everywhere. Your PR is welcome!
