### ISSUE TITLE
DataRequired claims IntegerField invalid when it contains "0"

### ISSUE THREAD

**Issue by richard-jones** [wtforms/wtforms#616]
### Actual Behavior

```python
import wtforms

class TestForm(wtforms.Form): 
    numeric = wtforms.fields.IntegerField(validators=[wtforms.validators.DataRequired()])                                                                                                                        

inst = TestForm(data={"numeric" : 0})                                                                                 
inst.validate()                                                                                                       

Out[6]: False
```

### Expected Behavior

As above, but with an output of `True` instead of `False`.

In this case my form will not accept the user entering the text "0" into an integer field (even though that may well be a valid input.  This occurs because the integer field coerces "0" to `0` and the `DataRequired` validator conducts a truthy test on the `data` property, which is overzealous in this instance.

Fix is probably to check for `None` or `""` or `[]` instead of relying on truthy-ness.

### Environment

* Python version: 3.5.2
* wtforms version: 2.2.1 (but I checked the latest version in the repo here, and it has the same issue)

**Comment by davidism** [comment]
Please check existing issues. Use `InputRequired` to check if input was given, use `DataRequired` to check the truthiness of that input. This may change in the future, but has already been reported and discussed multiple times.

**Comment by richard-jones** [comment]
ok, thank you, I'll look at `InputRequired`.  I did check the open issues, but didn't see anything, and as I assumed it was a bug didn't think to look at closed issues.
