### ISSUE TITLE
wtforms disable form caching

### ISSUE THREAD

**Issue by dizcza** [wtforms/wtforms#625]
Dear wtforms community,

Once the (stateful) `Form` is populated in a browser, it does not reflect the changes in the code anymore - it does not render the updates in `RadioField`, for example.
I created a minimal flask app that reproduces the behavior.

### Setup

```
templates/
├── upload.html
wordlists/
├── digits_8.txt
└── keyboard-walk.txt
app.py
```

`app.py` file:

```python
from pathlib import Path

from flask import Flask, request, render_template
from wtforms import Form, RadioField, SubmitField

app = Flask(__name__)


def wordlists_available():
    choices = []
    for wordlist in Path('wordlists').iterdir():
        choices.append((wordlist.name, wordlist.name))
    return choices


class UploadForm(Form):
    wordlist = RadioField('Wordlist', choices=wordlists_available(), default='digits_8.txt', description="The higher the rate, the better")
    submit = SubmitField('Submit')


@app.route('/', methods=['GET', 'POST'])
def upload():
    form = UploadForm()
    return render_template('upload.html', form=form)


if __name__ == "__main__":
    app.run(debug=True)
```

`templates/upload.html` content:
```html
<html>
<body>
    <h1>Upload</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {{ form.csrf_token }}
        {{ form.wordlist }}
        <p>{{ form.submit() }}</p>
    </form>
</body>
</html>
```

### Steps to reproduce

1. `python app.py`
2. Open a browser at localhost:5000
3. `rm wordlists/keyboard-walk.txt`
4. Refresh the browser or open it again at localhost:5000

### Expected Behavior

The browser shows the Upload form with only one available choice in the radio field - `digits_8.txt`.

### Actual behavior

The browser shows the cached Upload form with both `digits_8.txt` and `keyboard-walk.txt`. Any change to the files in `wordlists/` dir does not affect the rendered web page. Trying another browser, which I have not used with the app, while the app is running, shows the same behavior ---> it's on the app side.
![Screenshot from 2020-06-20 18-27-10](https://user-images.githubusercontent.com/7688337/85206638-baf3f980-b323-11ea-82ad-1a25b0d3abfe.png)

### Environment

* Python version: 3.8.3
* wtforms version: 2.3.1
* Flask: 1.1.2

### Additional info

I have been looking for the "cache" keyword in your documentation and have not found anything related. Do you guys internally cache fields without letting developers know how to turn the feature on and off or I'm doing something wrong? I found the [discussion](https://github.com/wtforms/wtforms/issues/311#issuecomment-266863293) saying

> I have a PR ready that caches the form.data dict and removes fields from the Form class attributes.

and also the [pull request](https://github.com/wtforms/wtforms/pull/568/files) that removes caching the errors.

**Comment by davidism** [comment]
You only define the choices once, when the form is defined.

The next version allows passing a callable that is called each time an instance is created.

For now, you would overwrite the init method to set the choices then.

**Comment by dizcza** [comment]
> The next version allows passing a callable that is called each time an instance is created.
> For now, you would overwrite the init method to set the choices then.

I don't understand the setup. Would you kindly provide me an example or a link where it's shown?
