### ISSUE TITLE
Website directs user to "new" old version

### ISSUE THREAD

**Issue by jms19** [wtforms/wtforms#629]
Viewer of
https://wtforms.readthedocs.io/en/2.3.x/

sees a banner at the top saying "Warning: This is an old version. The latest stable version is Version 2.2.1."

**Comment by jugmac00** [comment]
Ha, just noticed myself. Thanks for reporting, @jms19 

Just in case.. here is a screenshot.

![Screenshot from 2020-06-27 20-50-10](https://user-images.githubusercontent.com/9895620/85929797-ec3a6f80-b8b7-11ea-843a-4aed7acec49a.png)

**Comment by davidism** [comment]
fixed
