### ISSUE TITLE
Documentation is not up-to-date regarding email validation

### ISSUE THREAD

**Issue by jugmac00** [wtforms/wtforms#630]
wtforms 2.3.0 introduced the breaking change, that the email validation from then on needs a separate installed package.
https://github.com/wtforms/wtforms/pull/429/files

The current documentation does not reflect this, as email is still listed as a builtin validator
https://wtforms.readthedocs.io/en/2.3.x/validators/?highlight=email#wtforms.validators.Email

I wonder why the reviewer did not request a documentation update with the above mentioned PR.

**Comment by davidism** [comment]
That PR does have have new documentation, and the built docs reflect it.

> Requires email_validator package to be installed. For ex: pip install wtforms[email].

**Comment by jugmac00** [comment]
Thanks! I have not seen this. Still, I am wondering why it is called `built-in` validator, when you have to install a separate package - and yes, I had a look at the source code. Pretty funky. I only know this kind of optional features when using a colorize lib or similar.

I was pretty surprised when my Flask app broke, as I had no direct dependency on wtforms, but only on Flask-WTF.

So, I really need to pin the transitive dependencies.

Thanks again!
