### ISSUE TITLE
WTForms should have a way to validate input presence, not only "truthyness".

### ISSUE THREAD

**Issue by davidmoseler** [wtforms/wtforms#635]
DataRequired, as explained in the docs, checks, basically, "if field.data". Another important validation, though, would be to check if the field exists at all. For example, for BooleanFields, "DataRequired" is misleading, because one would think it checks if either true or false was provided, but in fact it is checking if the true value was provided. But it is often necessary to validate that the boolean value for that field was provided, not validate the boolean value itself. Another example would be to check if a string was provided, regardless of it being empty or not. Looking at the built in validators, it seems no validator provides this basic functionality.

**Comment by davidism** [comment]
Use `InputRequried`
