### ISSUE TITLE
documentation for "stable" is broken

### ISSUE THREAD

**Issue by jugmac00** [wtforms/wtforms#643]
Maybe related to #629 

I worked on a rather complex form today, so I did a lot of googling, and I noticed, that there are tons of links out there referencing the "stable" version of the documentation, which is broken.

So basically
- all results on Google
- a lot of results on StackOverFlow
- a lot of links in blog posts
all point to URLs like https://wtforms.readthedocs.io/en/stable/validators/ which are all broken.

![Screenshot from 2020-08-07 16-07-40](https://user-images.githubusercontent.com/9895620/89654127-78cd4a00-d8c8-11ea-9756-9b57a910da22.png)

Whether you decided to use a new naming scheme or whatever.. just wanted to make sure the big impact this action had.

I am not super familiar with sphinx and readthedocs, so I do not know whether a simple fix would be available.

**Comment by davidism** [comment]
There is no simple fix for this. We now use versions like `2.2.x` to track release branches, there's no way to add a redirect for `/stable` without having to remember to keep it updated for all time.

**Comment by azmeuk** [comment]
If there is nothing to be done I suggest to close the issue.
