### ISSUE TITLE
SelectField/RadioField behave like they are required when they are not

### ISSUE THREAD

**Issue by richard-jones** [wtforms/wtforms#669]
If you construct a `SelectField` or a `RadioField` with no validators (in particular, no "required" validator of any kind), and provide the selectable values in the `choices`, then validate the empty form it will fail to validate in a similar way to if the field were actually required.

My use case is that I have a radio with "yes" and "no" as options.  If you do not select either of these options, the field fails to validate, even though not answering the question is also valid.  This is because the `pre_validate` method of `SelectField` checks to see if the coerced data is one of the allowed choices (which are just "yes" and "no").  In this particular case, I can't just add the null choice (like, the empty string) to the list of choices, because I don't want to give the user 3 radio buttons, only the actual meaningful 2.

### Actual Behavior

```python
class TestForm(Form):
    radio = RadioField("radio", choices=[("yes", "yes"), ("no", "no")])

inst = TestForm(data={"radio": ""})
inst.validate() # returns false
```

### Expected Behavior

I'd expect it to validate, or for there to be a constructor argument which allows me to force it to overlook a value that's not a specified choice.

### Environment

* Python version: 3.5
* wtforms version: 2.2.1

### Workarounds

I've created this class which just masks the RadioField/SelectField behaviour:

```python
class UnconstrainedRadioField(RadioField):
    def pre_validate(self, form):
        return
```

You could probably also workaround with a custom widget that didn't render your first null choice.

**Comment by azmeuk** [comment]
Indeed `validate_choice` can help here. As it has been 3 years I will close this issue but don't hesitate to continue the discussion if you think this should be kept open.
