### ISSUE TITLE
jsonschema pydantic

### ISSUE THREAD

**Issue by goschtl** [wtforms/wtforms#670]
Hey,

does anyone have plans to create a wtforms BaseForm out of an pydantic BaseModel or an json-schema.
I looked a bit around there are some things which allows to get Fields out of an SQLAlchemy or other ORM's.

Does anyone thought about it?

Thanks for any answers?

Christian

**Comment by davidism** [comment]
No, we don't plan to do that here. You're welcome to create a library that combines WTForms with other libraries though.
