### ISSUE TITLE
Label using lazy_gettext and variable 

### ISSUE THREAD

**Issue by nathan30** [wtforms/wtforms#672]
### Actual Behavior

```python

import wtforms
class FacturationForm(Form):
    # The xml_index is mandatory when you create a new input class
    xml_index = 'facturationInfo'

    noCommands = BooleanField(
        lazy_gettext('INVOICE_WITHOUT_ORDER') + ' 1',
        render_kw={
            'checked': '',
            'onclick': "removeAllOrderNumber($(this), $('.MAIN_ORDER_0'))"
        },
    )
```

The problem is that if I add the "1" after lazy_gettext, the translation wasn't working and the label is INOVICE_WITHOUT_ORDER. If  I remove the "1", it's working well

Any idea ?

### Environment

* Python version: 3.8.5
* wtforms version: 1.0

**Comment by azmeuk** [comment]
From the [documentation](https://flask-babel.tkte.ch/index.html?highlight=lazy#using-translations):
>  Lazy strings will not be evaluated until they are actually used.

By concatenating another string `+ ' 1'` to your translated string, you force the resolution of the translation to happen too soon, at a moment where your translation context has not been initialized yet.




This seems not related to wtforms to me.
