### ISSUE TITLE
RadioField gets data "None" if no value provided

### ISSUE THREAD

**Issue by richard-jones** [wtforms/wtforms#673]
If you initialise a form with either no form data, or with a radio field missing from the form data, then the value of `data` after coerce is the string `"None"`.  I think that what's happening is that the default value `None` is being adopted as the value, and then passed through the `text_type` coerce function, giving us `"None"`.

### Actual Behavior

```python
class TestForm(Form):
    radio = RadioField("radio", choices=[("yes", "yes"), ("no", "no")])

inst = TestForm()
assert inst.radio.data == "None"
```

### Expected Behavior

I'd expect the value of `data` to be the actual default value, rather than the coerced default value, at least in the case where the default value is the NoneType

```python
class TestForm(Form):
    radio = RadioField("radio", choices=[("yes", "yes"), ("no", "no")])

inst = TestForm()
assert inst.radio.data is None
```

### Environment

* Python version: 3.5
* wtforms version: 2.2.1

### Workarounds

I've extended my custom Radio class from #669 to pre-check the value during `process_data` for being a NoneType:

```python
class UnconstrainedRadioField(RadioField):
    def pre_validate(self, form):
        return

    def process_data(self, value):
        if value:
            super(UnconstrainedRadioField, self).process_data(value)
        else:
            self.data = None
```

**Comment by dinosawrusrex** [comment]
I think from 2.3.x onwards this has been dealt with!
I use the older WTForms version for work and we have to handle this as well. Always a lovely find/what a pain!

**Comment by azmeuk** [comment]
Not a bug anymore with the last releases.
```python
import wtforms
>>> class TestForm(wtforms.Form):
...     radio = wtforms.RadioField("radio", choices=[("yes", "yes"), ("no", "no")])
>>> inst = TestForm()
>>> inst.radio.data is None
True
```
