### ISSUE TITLE
QuerySelectField raise error  sqlalchemy.exc.ProgrammingError

### ISSUE THREAD

**Issue by smaelc** [wtforms/wtforms#674]
###  sqlalchemy.exc.ProgrammingError
Hello,

I get an error when i enable QuerySelectField after submitted form.

`
....
from wtforms.ext.sqlalchemy.fields import QuerySelectField

class MemberModelView(ModelView)
...
form_extra_fields = {
        "role_id": QuerySelectField(
            _("Rôle"),
            query_factory=make_query_factory(Role),
            get_label="name",
            allow_blank=True,
            blank_text=(u"Select"),
            get_pk=lambda x: x.id,
            widget=Select2Widget(),
        )}
`
Helps please.

**Comment by smaelc** [comment]
<unprintable ProgrammingError object> shown

**Comment by azmeuk** [comment]
Please provide a reproducible example of the bug you are experiencing, ideally something a maintainer can copy/paste in a terminal.

Also, please use [github markdown](https://guides.github.com/features/mastering-markdown/) to format the code in your bug report.
