### ISSUE TITLE
Are tests currently broken for wtforms? 

### ISSUE THREAD

**Issue by jgarte** [wtforms/wtforms#687]
Hi, are tests currently broken for wtforms? 

I tried running the tests for wtforms with pytest. Some of the tests fail and some pass.

Here is a selection of the ones that I tested manually:

```
pytest -v tests/ # 5 ERRORS
pytest -v tests/test_csrf.py # 1 FAILED 8 PASSED
pytest -v tests/test_webob.py # PASSED
pytest -v tests/test_form.py # 5 FAILED 18 PASSED
pytest -v tests/test_i18n.py # 11 PASSED
```

**Comment by azmeuk** [comment]
You can use `tox` to run the tests instead of directly `pytest`. Then everything will be green.
