### ISSUE TITLE
ETA for new release tags

### ISSUE THREAD

**Issue by anthraxx** [wtforms/wtforms#691]
Hey folks, thanks a lot for your great work here! 

Is there any ETA for the new release tree? :cat:

**Comment by davidism** [comment]
When it's ready and we have time. Sorry, as volunteers we can't make a more accurate statement than that.

**Comment by anthraxx** [comment]
thanks. but no need to be snarky i'm a volunteer as well and spending half my life on open source

**Comment by azmeuk** [comment]
Blockers for the next release are #402 and #662
