### ISSUE TITLE
Documentation mistake in "Fields With Custom Constructors"

### ISSUE THREAD

**Issue by smmalmansoori** [wtforms/wtforms#701]
### Background

[Fields With Custom Constructors](https://wtforms.readthedocs.io/en/2.3.x/fields/#fields-with-custom-constructors) indicates that an empty string should be the default value for the _label_ parameter.

This is directed implicitly in the code sample:

```python
class BetterTagListField(TagListField):
    def __init__(self, label='', validators=None, remove_duplicates=True, **kwargs):
```

and explicitly after the code sample:

> When you override a Field’s constructor, to maintain consistent behavior, you should design your constructor so that:
> * You take label=’‘, validators=None as the first two positional arguments

### Problem

This doesn't maintain consistent behavior. It results in no text being rendered if no label is provided instead of the default behavior of capitalizing the variable name of the field (`username -> Username`, `first_name -> First Name`, etc.).

### Solution

Update the documentation to state that the constructor's _label_ parameter should have `None` as its default value. This produces the expected behavior and is consistent with the `Field` base class.

**Comment by azmeuk** [comment]
Thank you for your report!
