### ISSUE TITLE
Can one explain to me how form.validate works?

### ISSUE THREAD

**Issue by Gresliebear** [wtforms/wtforms#702]
I have been passing in the expected parameters into form object and its returning false and I have no idea which field is specifically failing why its return statement just false?

**Comment by davidism** [comment]
Check form.errors.

**Comment by Gresliebear** [comment]
Thank you, I have tried that but it returns empty 

            print(form.is_submitted())
            print(form.errors)
            print(form.validate())
           

True
{}
False
failed to validate or create a account

Heres the post request
        {'token_id': 'csrf_token_17c1de18-1c8d-46fe-bcb8-a2eb01ab723f', 'csrf_token': 'IjBhMzQ3NTcxNmNmOGUyODFhMzQxNzdhMTg5N2FhM2Q5NjQ5NTBmYWMi.YQCfeA.oUCse0394Xf-6Mi1XIWL7FmF3ks', 'username': 'test', 'email': 'test@gmail.com', 'password': 'test', 'confirm_password': 'test', 'submit': 'Register'}

Heres the form.data 
{'username': 'test', 'email': 'test@gmail.com', 'password': 'test', 'confirm_password': 'test', 'submit': True, 'csrf_token': 'IjBhMzQ3NTcxNmNmOGUyODFhMzQxNzdhMTg5N2FhM2Q5NjQ5NTBmYWMi.YQCfeA.oUCse0394Xf-6Mi1XIWL7FmF3ks'}

**Comment by Gresliebear** [comment]
So I have no idea why this is triggering false is something happening in the background that I haven't found in the docs?

**Comment by Gresliebear** [comment]
https://stackoverflow.com/questions/11653526/django-empty-form-errors

I think I figured it out basically I am passing a JSON data into form.data but this makes the form unbound which means the forms are always invalided so even elif request.POST is set to None.
