### ISSUE TITLE
DataRequired not work on readonly StringField

### ISSUE THREAD

**Issue by animax1991** [wtforms/wtforms#711]
### Actual Behavior
The stringField I set readonly to True, so no one can input data on that. I used Javascript to calculate the total money to pay and fill that stringField. Everything is fine, until client use backward button on browser. Other StringField is autocomplete with previous data they just input except the readonly StringField. Then, when I click on submit button, the data is still submit to the server, instead of triggering DataRequired on that readonly StringField.

Is there any solutions for this case ?

The code:
`    money_receive = StringField('Số tiền nhận', validators=[DataRequired()],render_kw={"placeholder": "0"})
`
`                                    {{ form.money_receive(class="form-control form-control-lg" ,readonly=True) }}
`

### Expected Behavior
trigger DataRequired on readonly StringField, when there is no data on it.

```python
"please fill out this field" should be pop up.

### Environment
* Python version: 3.9
* wtforms version: 2.3.3

**Comment by azmeuk** [comment]
I don't understand the issue you are reporting. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
