### ISSUE TITLE
Fix DateTimeField

### ISSUE THREAD

**Issue by paveL1boyko** [wtforms/wtforms#723]
![image](https://user-images.githubusercontent.com/43044519/147347063-e03e1b18-a047-4dad-bdb7-0352bb040bb9.png)
42 line overrides 32 and 
![image](https://user-images.githubusercontent.com/43044519/147347125-49bb7cb7-9def-497c-a7f4-c2c9df1eb9d9.png)
```
    def _value(self):
        if self.raw_data:
            return " ".join(self.raw_data)
        return self.data and self.data.strftime(self.format[0]) or ""
```
this code return % need fix 

![image](https://user-images.githubusercontent.com/43044519/147347544-c2d4419b-0f6f-4d55-960d-dac0e2b163c8.png)

**Comment by paveL1boyko** [comment]
ping @funelie

**Comment by azmeuk** [comment]
Please write a reproducible piece of code that explains your bug. Ideally something I can just copy and paste into a python REPL. Also, I need more information because I just have no idea what you are talking about.
We can reopen the ticket then.

**Comment by paveL1boyko** [comment]
```
from datetime import datetime

from flask import Flask
from flask_admin.form import DateTimeField
from flask_sqlalchemy import SQLAlchemy
from wtforms import Form

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////tmp/test.db'
db = SQLAlchemy(app)


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    created_dt = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)


class TestForm(Form):
    created_dt = DateTimeField('Test')


user = User()
form = TestForm(obj=user)
form.created_dt.process_data(datetime.utcnow())
assert form.created_dt._value() == '%'
```

**Comment by paveL1boyko** [comment]
ping @funelie

**Comment by azmeuk** [comment]
Ok this is better, thank you for taking the time to write this snippet.
Now I can confirm the behavior is the same on my computer.
It looks like there is [an issue](https://github.com/flask-admin/flask-admin/issues/2189) with DateTimeField and wtforms 3 on the flask-admin side. I have not tested the patch submitted there, but it seems OK to me.

**Comment by paveL1boyko** [comment]
yea, they fix it)
https://github.com/flask-admin/flask-admin/pull/2190
