### ISSUE TITLE
Support fields for week, month and color

### ISSUE THREAD

**Issue by PanderMusubi** [wtforms/wtforms#725]
Please, support fields for week, month and color. See the example at https://getbootstrap.com/docs/5.1/content/reboot/?optionsRadios=option1#forms

        <p>
          <label for="week">Example week</label>
          <input type="week" id="week">
        </p>
        <p>
          <label for="month">Example month</label>
          <input type="month" id="month">
        </p>
        <p>
          <label for="color">Example color</label>
          <input type="color" id="color">
        </p>

**Comment by azmeuk** [comment]
Hi. Thank you for your contribution. The `MonthField` already exists, even if it was not documented, though it is fixed now.

For the record:
- [The MDN page on week input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/week)
- [The MDN page on color input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/color)

**Comment by PanderMusubi** [comment]
Is a PR welcomed for week and color?

**Comment by PanderMusubi** [comment]
Thanks for merging the related PR and other PRs. Since the last release is one year ago, could you please make a new release so PyPI will include these these contributions?

**Comment by azmeuk** [comment]
@PanderMusubi are you interested in reviewing #765?

**Comment by PanderMusubi** [comment]
Looks good. Perhaps refactor

    import datetime

to

     from datetime.datetime import strptime

@greyli can you have look too?
