### ISSUE TITLE
wtforms is not xhtml-compatible

### ISSUE THREAD

**Issue by hazorus** [wtforms/wtforms#731]
Documentation says:
"Widgets are classes whose purpose are to render a field to its usable representation, usually XHTML"

All input-elements generated by wtforms are invalid xhtml, because /> is missing (<input ...> vs <input ... />).  Required-attributes are also invalid.

**Comment by davidism** [comment]
Happy to  consider a PR that changes it to "HTML".

**Comment by hazorus** [comment]
How about making wtforms really xhtml-compatible? it would not need many changes. I am having trouble because of this incompatibility. For earlier wtforms there was a 
Flask-WTF-Polyglot -library that fixed this but it does not work with the new version of wtforms.

**Comment by davidism** [comment]
We don't plan to support XHTML at this time. We will focus on HTML only.

**Comment by yggi49** [comment]
If it helps, the [WTForms-Polyglot](https://pypi.org/project/wtforms-polyglot/) and [Flask-WTF-Polyglot](https://pypi.org/project/flask-wtf-polyglot/) packages should now work with WTForms 3.x.
