### ISSUE TITLE
Title attribute 

### ISSUE THREAD

**Issue by SofianeB** [wtforms/wtforms#745]
Hi, 

is it possible to add title attribute like in html?

HTML example:
```
<input type="text" title="description" name="text>abc</label>
```
I tried this but it does not work:
```
field1 = SelectField("Field1", description="description")
```

**Comment by azmeuk** [comment]
You can use [render_kw](https://wtforms.readthedocs.io/en/3.0.x/fields/?highlight=render_kw#wtforms.fields.Field) to achieve this.

```python
field1 = SelectField("Field1", render_kw={"title":"description"})
```
