### ISSUE TITLE
How to generate swagger api docs from wtfroms?

### ISSUE THREAD

**Issue by thinker3** [wtforms/wtforms#746]
Now I use flask_restx to write swagger schemas, but it's validation is not very good.

**Comment by davidism** [comment]
This is outside the scope of WTForms itself, it would be an additional extension someone would need to write and maintain. As in, this would be appropriate for an API extension. There are plenty of other extensions besides Flask-RestX. Take a look at Flask-Rebar, APIFlask, Flask-RestY, Flask-Smorest, etc.
