### ISSUE TITLE
validator Optional(strip_whitespace=True/False) and whitespace 

### ISSUE THREAD

**Issue by hexkey** [wtforms/wtforms#751]
Hello,

Is there a logical explanation, why if field is set to be Optional in validation, all validation checks are skipped? 

User can simply enter white space as input and no option for validation is available. Imho _all_ fields should be checked and validated even Optional ones. Also the parameter "strip_whitespace" is misleading. 

Thank you.

**Comment by azmeuk** [comment]
The very point of `Optional` is to stop the validation chain when data is absent.

> User can simply enter white space as input and no option for validation is available. 

Again, this is the point of `Optional`. I am not sure what you would have it to do?

> Also the parameter "strip_whitespace" is misleading.

Why that?

```python
import wtforms
from werkzeug.datastructures import ImmutableMultiDict
>>> class F(wtforms.Form):
...     foo = wtforms.IntegerField(validators=[wtforms.validators.Optional(), wtforms.validators.NumberRange(5, 10)]
... )
>>> F().validate()
True
>>> F(ImmutableMultiDict({"foo":""})).validate()
True
>>> F(ImmutableMultiDict({"foo":" "})).validate()
True
>>> F(ImmutableMultiDict({"foo":"0"})).validate()
False
>>> F(ImmutableMultiDict({"foo":"10"})).validate()
True
```
