### ISSUE TITLE
Missing a way to disable csrf for testing

### ISSUE THREAD

**Issue by iameru** [wtforms/wtforms#757]
I found no way to turn off csrf if testing with pytest. Am I missing something? 
Functional tests and app in production actually produce CSRF, thats all good. however I wan't to disable this for testing because all validates fail in testing as testing can't handle csrf. (this might be a ["workaround"](https://gist.github.com/singingwolfboy/2fca1de64950d5dfed72?permalink_comment_id=3952788)   for all you interested - I wanted to go the "quick" way and disable csrf in testing and here I am 3 hours later).

Following [meta.rst](https://github.com/wtforms/wtforms/blob/master/docs/meta.rst) and [csrf.rst](https://github.com/wtforms/wtforms/blob/master/docs/csrf.rst) my Class looks like this. I use Flask so I return session. 

`app/form/form.py`
```python
...
from app.config import Config
class BaseForm(ModelForm):
    class Meta:
        csrf = True
        csrf_class = SessionCSRF
        csrf_secret = Config.CSRF_SECRET_KEY

        @property
        def csrf_context(self):
            return session
```
`app/__init__.py` Inititiation:
```
import os
from flask import Flask
from app.config import Config

def create_app(test_config=None):

    app = Flask(__name__, instance_relative_config=True)

    app.config.from_object(Config)

    if test_config:
        app.config.from_mapping(test_config)

....#blueprints and blabla
```
`config.py` for the staging and production apps
```
from dotenv import dotenv_values
env = dotenv_values(".env")
class Config:

    SECRET_KEY = env.get("SECRET_KEY")
    CSRF_SECRET_KEY = env.get("CSRF_SECRET_KEY").encode()
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_DATABASE_URI = "sqlite:///../instance/database.sqlite"
```
`conftest.py` for pytest, here you see the apparently legacy config commands which should stop CSRF according to half of the population of the internet
```
import pytest

from app import create_app
from app.db import db

test_config = {
    "SECRET_KEY": "TEST_CONFIG",
    "TESTING": True,
    "SQLALCHEMY_DATABASE_URI": "sqlite:///:memory:",
    "WTF_CSRF_ENABLED": False,
    "WTF_CSRF_CHECK_DEFAULT": False,
    "WTF_CSRF_SECRET_KEY":None,
    "CSRF_SECRET_KEY":None,
}

@pytest.fixture(scope="session")
def test_app():

    test_app = create_app(test_config=test_config)
    with test_app.app_context():

        db.create_all()
        yield test_app
        db.drop_all()
```

None of these apparently legacy (?) config parameters for the app factory of flask switch off csrf globally for testing - forms expect csrf tokens to be validated `True`

Is there no way to disable CSRF at app initiation, what am I missing?

`wtforms==3.0.1 ; python_version >= "3.8" and python_version < "4.0"`

**Comment by ewie** [comment]
Config `WTF_CSRF_ENABLED` is part of Flask-WTF: https://flask-wtf.readthedocs.io/en/1.0.x/form/#secure-form.
Have you tried that instead of plain WTForms since you're already using Flask?
