### ISSUE TITLE
Improving the documentation

### ISSUE THREAD

**Issue by Hvass-Labs** [wtforms/wtforms#772]
Thanks for making WTForms!

Please improve the documentation because core aspects are impossible to understand.

Let me explain:

I have made several custom fields and validators, and built a somewhat sophisticated GUI on top of WTForms for more advanced HTML input-forms. But honestly, I don't understand how WTForms really works and it is a major problem, because I sometimes get strange behavior in my custom fields.

For example, the docs for `process_formdata` [here](https://wtforms.readthedocs.io/en/3.0.x/fields/#wtforms.fields.Field.process_formdata) say: *"Process data received over the wire from a form."* But what does *"over the wire"* mean?!? Please don't use such casual language in documentation as it is very hard to understand what you really mean.

Another example is `raw_data` [here](https://wtforms.readthedocs.io/en/3.0.x/fields/#wtforms.fields.Field.raw_data) whose docs say: *"If form data is processed, is the valuelist given from the formdata wrapper. Otherwise, raw_data will be None."* Pardon me but this is complete gibberish!

And the problem is made worse when your source-code and examples are inconsistent. For example, [this tutorial](https://wtforms.readthedocs.io/en/3.0.x/fields/#custom-fields) shows the following code used to create a custom WTForms field:

    def _value(self):
        if self.data:
            return ', '.join(self.data)
        else:
            return ''

But when looking in your actual implementation, the code typically looks like [this](https://github.com/wtforms/wtforms/blob/master/src/wtforms/fields/numeric.py#L66-L71):

    def _value(self):
        if self.raw_data:
            return self.raw_data[0]
        if self.data is not None:
            return str(self.data)
        return ""

But it's impossible to understand from your docs when to use `self.data` and when to use `self.raw_data` because their semantics are unclear from the documentation.

It appears that the dev-team is also confused about how this is supposed to work, see e.g. #662.

Please consider improving the documentation and possibly also the code-samples, so the semantics are more clear, and we can build our custom extensions correctly.

Thanks!

**Comment by davidism** [comment]
Happy to review PRs, but "just improve everything" isn't an actionable issue on its own, so closing this.

**Comment by Hvass-Labs** [comment]
@davidism I was trying to be polite and constructive, yet you closed the issue within 2 minutes of me opening it with a somewhat rude response. I have seen you do the same to others who have posted here about serious problems in your library. That's probably why WTForms is a complete mess of undocumented spaghetti-code that the dev-team doesn't even understand. Please refrain from responding any further here, as you obviously won't help.

@azmeuk You seem to have studied this problem intently. Could you improve the documentation and code samples so it is easier to understand for others, so we don't have to spend a very long time trying to understand the undocumented spaghetti-code, or reading long GitHub threads? Thanks!
