### ISSUE TITLE
inputmode numeric on IntegerField by default

### ISSUE THREAD

**Issue by laureanorp** [wtforms/wtforms#776]
### Suggestion, not issue

Hello everyone!

Context: When using `'inputmode': 'numeric'` in `render_kw` of a field, that field will pop up a special, number-only keyboard on smartphones. It doesn't affect desktop websites as far as I know. 

![image](https://user-images.githubusercontent.com/14150766/221850470-17ed48ef-6e52-4bc5-b667-4243ba5dac7d.png)

It came to my attention that the class `IntegerField` doesn't include the `render_kw` `'inputmode': 'numeric'` by default, but it has to be added manually. Is this a design decision? I think it would be an accesbility/usability improvement if this was included by default.

Thanks in advance for your response.

**Comment by azmeuk** [comment]
At least with firefox on mobile, the numeric input mode is implied by `<input type="number">` without the need to use `inputmode`.  I am not sure if this behavior is part of the spec or not. MDN does not say much about this on the [inputmode](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) and [input type="number"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) pages. I have not checked with other browsers, did you?

**Comment by laureanorp** [comment]
Yeah I just checked and I was wrong, even if the `'inputmode': 'numeric'` argument is not added, the input number will pop up the correct keyboard by default on mobile. Thanks!

On the input type number docs I can also see:

<img width="793" alt="image" src="https://github.com/wtforms/wtforms/assets/14150766/bcf1794d-2ba1-46f7-bf9f-72243e1bb3db">
