### ISSUE TITLE
Error when a field is named `meta`

### ISSUE THREAD

**Issue by tcompa** [wtforms/wtforms#791]
Hi there, and thanks for your support.

I realized that if a form field is named `meta`, this leads to a name clash with the actual `meta` attribute of the `Form` object. I'm wondering whether this use case could be supported, or otherwise whether an informative error message could be raised.

For the record, this same issue was mentioned in https://github.com/aminalaee/sqladmin/issues/539.

### Actual Behavior

```python
from wtforms import Form, StringField

class RegistrationForm(Form):
    username = StringField('Username')
    meta = StringField('Meta')

form = RegistrationForm()
```

```python traceback
Traceback (most recent call last):
  File "/somewhere/test.py", line 7, in <module>
    form = RegistrationForm()
  File "/somewhere/venv/lib/python3.10/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/somewhere/venv/lib/python3.10/site-packages/wtforms/form.py", line 286, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/somewhere/venv/lib/python3.10/site-packages/wtforms/form.py", line 106, in process
    formdata = self.meta.wrap_formdata(self, formdata)
AttributeError: 'StringField' object has no attribute 'wrap_formdata'
```

The reason for this behavior is clear from this snippet (https://github.com/wtforms/wtforms/blob/master/src/wtforms/form.py#L282-L285):
```python
        for name, field in self._fields.items():
            # Set all the fields to attributes so that they obscure the class
            # attributes with the same names.
            setattr(self, name, field)
```

### Expected Behavior

Either one of
1. Using `meta` for a field is supported. This could be achieved by renaming `meta` into something more specific (similar to `_wtforms_meta`), although this is admittedly not a trivial change.
2. When trying to name a field `meta`, wtforms raises an informative error (anything on the line of `ValueError("Naming a field meta is not supported")`).

### Environment

* Python version: 3.10.6
* wtforms version: 3.0.1

**Comment by tcompa** [comment]
Thanks for your feedback!

Changing the model-field names is not something we plan to do (since this applies to an existing code base), but it's good to know a possible workaround.

**Comment by davidism** [comment]
It's the form field attribute, not the modern field name.

**Comment by tcompa** [comment]
> It's the form field attribute, not the model field name.

My bad, I mixed up the answer here with the one in the related issue over at [sqladmin](https://github.com/aminalaee/sqladmin).

More in detail:
In our use case, we are not creating forms ourselves, but rather through sqladmin. And sqladmin sets the form-attribute names to match the names of the (e.g. sqlalchemy) model. I think the relevant bit is [the following snippet from the sqladmin `get_model_form` function](https://github.com/aminalaee/sqladmin/blob/978cdd6587c7fc8345076393ae6774cddbdcd48c/sqladmin/forms.py#L589):
```python
    attributes = []
    names = only or mapper.attrs.keys()
    for name in names:
        if exclude and name in exclude:
            continue
        attributes.append((name, mapper.attrs[name]))

    field_dict = {}
    for name, attr in attributes:
        field_args = form_args.get(name, {})
        field_widget_args = form_widget_args.get(name, {})
        label = column_labels.get(name, None)
        override = form_overrides.get(name, None)
        field = await converter.convert(
            model=model,
            prop=attr,
            engine=engine,
            field_args=field_args,
            field_widget_args=field_widget_args,
            label=label,
            override=override,
            form_include_pk=form_include_pk,
            form_ajax_refs=form_ajax_refs,
        )
        if field is not None:
            field_dict[name] = field

    return type(type_name, (form_class,), field_dict)
```
where the default is `form_class=wtforms.Form`.

For this reason, I have no direct control on the details of how the form is created. A [full example with sqladmin](https://github.com/aminalaee/sqladmin/issues/539#issue-1788972473) then fails, when my (sqlalchemy) model has a `meta` field, because this clashes with the reserved `meta` attribute of the `Form` object.

A similar workaround to the one you suggested (using `_meta`) [was also suggested at the level of the sqlalchemy-model field names](https://github.com/aminalaee/sqladmin/issues/539#issuecomment-1621225555), and this explains my previous comment that for us it would not be trivial to change model-field names in an existing project.

Apologies if I mixed up the two issues.
