### ISSUE TITLE
Failure/error in rendering the Field value (DecimalField)

### ISSUE THREAD

**Issue by HK-Mattew** [wtforms/wtforms#805]
### Failure/error in rendering the Field value (DecimalField)

```python
# Here is an example:

from wtforms import Form, DecimalField, validators

class MyForm(Form):

    #CPC Part
    cpc = DecimalField(
        label='CPC',
        validators=[
            validators.DataRequired(),
            validators.NumberRange(
                min=0.01
            )
        ],
        render_kw={
            'placeholder': f'Min: 0.01 USD'
        }
    )
    
form = MyForm(data={'cpc': 0.03})
print(form.cpc.data)
# Result: 0.03
print(form.cpc.__html__())
# Result:
<input id="cpc" min="0.01" name="cpc" placeholder="Min: 0.01 USD" required step="any" type="number" value="0.00">
```

**See that the rendered value of form.cpc.__html__() is 0.00. This is wrong**

### Environment

* Python version: 3.8.18
* wtforms version: 3.0.1

**Comment by azmeuk** [comment]
Hi
Running python 3.8.18 on the 3.0.1 tag, and copy/pasting your snippet, I cannot reproduce this bug, and the value I see `0.03`. I am not sure what the difference come from.
Are you sure this snippet executes "as is"? Did you try it on other execution contexts? (different python version, different OS etc?)

**Comment by HK-Mattew** [comment]
I was racking my brain to find out the real reason this failure happened and I found it. See my code for explanations.
 
 
 ```python
 
from wtforms import Form, DecimalField, validators


MIN_CPC = 0.0035


class MyForm(Form):

    #CPC Part
    cpc = DecimalField(
        label='CPC',
        validators=[
            validators.DataRequired(),
            validators.NumberRange(
                min=MIN_CPC
            )
        ],
        render_kw={
            'placeholder': f'Min: {MIN_CPC} USD'
        }
    )



"""
[ Works correctly ]:
"""
form = MyForm(data={'cpc': 0.01})

print('cpc from form: ', form.cpc.data)
#Result: cpc from form:  0.01

print(form.cpc.__html__())
# Result: <input id="cpc" min="0.0035" name="cpc" placeholder="Min: 0.0035 USD" required step="any" type="number" value="0.01">


"""
[ Rendering failed ]:
"""
form = MyForm(data={'cpc': 0.001}) # * Values with more than 2 decimal places. *

print('cpc from form: ', form.cpc.data)
#Result: cpc from form:  0.001

print(form.cpc.__html__())
# Result: <input id="cpc" min="0.0035" name="cpc" placeholder="Min: 0.0035 USD" required step="any" type="number" value="0.00">

"""
The failure happens when I enter values with more than 2 decimal places.

*form.cpc.data* works correctly.
*form.cpc.__html__()* Does not work correctly.
"""

 ```

**Comment by azmeuk** [comment]
https://github.com/wtforms/wtforms/blob/e205a991470f2054148734f6aa67ca49964b76ee/src/wtforms/fields/numeric.py#L99-L102

Just set `places` to 3 or None and your snippet works.

**Comment by HK-Mattew** [comment]
That worked.

But I just want to leave my opinion. In my opinion, I think this option should be None by default. Because if Field has decimal values, I believe that it should not reduce the decimal places of the values to 2 by default. Well, I don't see any sense in that. (But I may be wrong. I honestly don't know why this is active as 2 by default).
