### ISSUE TITLE
SelectMultipleField overrides default, keyword and obj provided values when empty post data is provided to the form

### ISSUE THREAD

**Issue by andycaine** [wtforms/wtforms#821]
### Actual Behavior

```python
>>> class DummyPostData(dict):
...     def getlist(self, key):
...         v = self[key]
...         if not isinstance(v, (list, tuple)):
...             v = [v]
...         return v
...
>>> import wtforms
>>> class F(wtforms.Form):
...     foo=wtforms.SelectMultipleField([('bar', 'Bar'), ('baz', 'Baz')])
...
>>> import dataclasses
>>> @dataclasses.dataclass
... class C:
...     foo: list[str]
...
>>> obj = C(foo=['bar'])
>>> post_data = DummyPostData([])
>>> form = F(post_data, obj)
>>> print(form.foo.data)
[]
```

### Expected Behavior

```python
>>> class DummyPostData(dict):
...     def getlist(self, key):
...         v = self[key]
...         if not isinstance(v, (list, tuple)):
...             v = [v]
...         return v
...
>>> import wtforms
>>> class F(wtforms.Form):
...     foo=wtforms.SelectMultipleField([('bar', 'Bar'), ('baz', 'Baz')])
...
>>> import dataclasses
>>> @dataclasses.dataclass
... class C:
...     foo: list[str]
...
>>> obj = C(foo=['bar'])
>>> post_data = DummyPostData([])
>>> form = F(post_data, obj)
>>> print(form.foo.data)
['bar']
```

When empty form data is supplied, the data provided in the object should be used and not overridden by the empty form data. This is what would happen with other fields, for example wtforms.SelectField:

```python
>>> class DummyPostData(dict):
...     def getlist(self, key):
...         v = self[key]
...         if not isinstance(v, (list, tuple)):
...             v = [v]
...         return v
...
>>> import wtforms
>>> class F(wtforms.Form):
...     foo=wtforms.SelectField([('bar', 'Bar'), ('baz', 'Baz')])
...
>>> import dataclasses
>>> @dataclasses.dataclass
... class C:
...     foo: str
...
>>> obj = C(foo='bar')
>>> post_data = DummyPostData([])
>>> form = F(post_data, obj)
>>> print(form.foo.data)
'bar'
```

This behaviour also means that the pattern in the WTForms documentation (a common form handling pattern in my experience) works as expected, where an empty post data object is passed on an initial get request and populates the initial form with data from the object (https://wtforms.readthedocs.io/en/3.1.x/crash_course/#how-forms-get-data):

```python
def change_username(request):
    user = request.current_user
    form = ChangeUsernameForm(request.POST, user, username='silly')
    if request.method == 'POST' and form.validate():
        user.username = form.username.data
        user.save()
        return redirect('change_username')
    return render_response('change_username.html', form=form)
```

As things stand, if you use this pattern with a wtforms.MultipleSelectField, the data provided from the object would be overridden (as well as data and default inputs).

Original PR for this here https://github.com/wtforms/wtforms/pull/820#issuecomment-1872240529

### Environment

* Python version: 3.9
* wtforms version: 3.1.1

**Comment by davidism** [comment]
> When empty form data is supplied, the data provided in the object should be used and not overridden by the empty form data.

This is incorrect, although it is a common misunderstanding. You can search the issue tracker for a history of this coming up and being answered.

**Comment by andycaine** [comment]
> > When empty form data is supplied, the data provided in the object should be used and not overridden by the empty form data.
> 
> This is incorrect, although it is a common misunderstanding. You can search the issue tracker for a history of this coming up and being answered.

Ok I can now see some of the issues with just taking obj data when empty form data is passed in, although tbh I can't find a clear answer.  Does this then mean there is a bug with the SelectField implementation - in that it *does* use obj data when passed empty form data (or a missing key)?  StringField seems to do the same.  And also a bug in the docs I referenced?  In that the request should be checked to see if it is a form submission before passing the associated data, rather than passing in post data regardless of request type?

**Comment by davidism** [comment]
There is no concept of a request in WTForma, it is framework agnostic.

**Comment by andycaine** [comment]
Yeah I know that, I was referring to the docs I referenced which shows an example of how to use WTForms, passing POST data through without first checking that it's a POST request.
