### ISSUE TITLE
Question: Is it possible to create a dynamic/adaptive forms with WTForms?

### ISSUE THREAD

**Issue by hasansezertasan** [wtforms/wtforms#825]
I'm sorry if the title wasn't clear enough but I have an example that demonstrates what I need.

I have an example that I built using [json-editor/json-editor](https://github.com/json-editor/json-editor) and JSON Schema.

Here is the direct link to that example: [click](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2GG8EcWpUEEF4JwB3ei4sAFYQNjAqACssbzVxfGiwWhz4IQNxCpBERKwDVFAAEjF+BlAAQTJ8ROJ8gBEpfBgutHZOCEjYekGQAmJd2ChJHIA5IixumM2cx0p4AHMQAF82dHJV0COTlBAAVQ+V2iN1+dxgjxerxAwgAjugYMIRKgANp7C7dd5dAC6bG+l1+Uycs0CUEWThWQJB4BqdSgLzYAEkDA8sGTlp91hEojAdmtMYdgj9/oDccD8T0KOCnlCYMzcNd8V9BeKmfgWQACAAqYsp4rBEOeUNh8MRKPkIpAsrV8p1OJAeJyqpZbIpoqpVVq9XpIE1WEMpKWFLW4U23N5Xz9dLWDt+vv9utukoNRqwcIRWCRKFRdHjdpjPsjLq6bvFHtpkLYIa2PPG9uVAuO4s19ZLifu0p8CDo+V2+Hg0QA8vwUcNhMPfgBiAD0IwEiCnhJmZjmAfJXVeo4EOWns7GU7jq/Z9M345AO9G86drMD67z9d+AGEuySK9DUyaM2aHZ38i+742cgABTARwE1+MsvShRAzDAAocEiThyAYS1f3IGZYAQK4zH6cUqDAMAoDufAIAAFkhIA==)

Here are the screenshots:

![image](https://github.com/wtforms/wtforms/assets/13135006/ac6adee6-634b-4d6c-bc4f-bc410512ddb5)

As you can see, there is a dropdown called "Content" which lets you choose the type of content. Depending on the content type, the form changes.

![image](https://github.com/wtforms/wtforms/assets/13135006/1e402c4a-14c8-4edc-a33b-04de9d111c0c)

In this image, I chose "Attachment", which requires some fields that other types don't have.

![image](https://github.com/wtforms/wtforms/assets/13135006/d7c129b6-d992-4c2d-81eb-00ac17b302c8)

In this image, I chose the "Text" type, and the form automatically transforms.

![image](https://github.com/wtforms/wtforms/assets/13135006/8310e4ad-cfa7-4aae-92a4-004834ea502b)

As you can see, if I chose the "Image" type, the form adopts its fields.

The best workaround I can think of to implement something similar to this is to create three different forms and put them in separate tabs but if someone fills the form and decides to change the type of the form, the filled part will not be in other type. Is there any implementation or a way to make this kind of form in WTForms?

**Comment by davidism** [comment]
Yes, it is possible to process dynamic forms using field lists and nested form fields. You still need JavaScript to handle building the dynamic changes to the forms.

**Comment by hasansezertasan** [comment]
I wanted to stay in `*.py` files and do the things I wanted to do without creating any front-end files.

For anyone who met this issue: this can be easily done without writing a single line of JavaScript using AlpineJS or hyperscript.

Just use the `render_kw` argument of the fields, then you are good to go!

As for the validation, use `If` validator from [wtforms-components](https://github.com/kvesteri/wtforms-components).
