### ISSUE TITLE
Missing period for two messages

### ISSUE THREAD

**Issue by PanderMusubi** [wtforms/wtforms#826]
This is a very minor issues. Please the the lines

https://github.com/wtforms/wtforms/blob/master/src/wtforms/validators.py#L698

and

https://github.com/wtforms/wtforms/blob/master/src/wtforms/validators.py#L714

All the other messages have a period at the end of the line (search on gettext) but these two lines not. Please fix or let me know if I can make a PR for it.

**Comment by azmeuk** [comment]
Thank you for the issue. Sure please open a PR.
