### ISSUE TITLE
Email Validator Regex doesn't accept new TLDs

### ISSUE THREAD

**Issue by phistrom** [wtforms/wtforms#95]
The regular expression for the [Email validator](https://github.com/wtforms/wtforms/blob/master/wtforms/validators.py#L288) appears to be `^.+@[^.].*\.[a-z]{2,10}$`

This regular expression will not match several currently valid top level domains according to the [IANA](http://data.iana.org/TLD/tlds-alpha-by-domain.txt) either due to being longer than 10 characters (**.photography**, **.versicherung**, etc) or containing non-latin-letters (**.xn--c1avg**).

I would suggest making it `^.+@[^.].*\.[\-\w]{2,63}$` for a minimum of 2 characters to the [DNS label maximum of 63](http://en.wikipedia.org/wiki/Domain_Name_System#cite_ref-rfc1034_1-2) and to include numbers and hyphens being in the TLD.

**Comment by nulldata** [comment]
var regexpEmail=/^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,7}(?:\.[a-z]{2})?)$/i;

**Comment by janwerkhoven** [comment]
@nulldata That regex does not match `my.long.name@dep.gov.com`
